#line 2 "src-generated/ugbc.yy.c"

#line 4 "src-generated/ugbc.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 223
#define YY_END_OF_BUFFER 224
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[682] =
    {   0,
        0,    0,  224,  222,  221,    1,    1,  222,   13,   20,
      222,    4,    5,   19,    9,    6,   10,   22,  218,  218,
      218,  218,    3,    2,   14,    7,   16,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  164,  214,  214,  214,  214,  214,  214,
       23,  222,   24,   21,  214,  221,    1,    0,  215,    0,
        0,    0,   11,   12,  218,  218,  218,    0,   15,   18,
        8,   17,  214,  214,  214,  214,   29,   31,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,   73,  214,

      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  103,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  127,  214,
      214,  214,  214,  214,  135,  137,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  189,  214,
      214,  214,  193,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,    0,    0,  220,
        0,    0,    0,   28,   32,   34,  214,   30,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,

       49,  214,   53,  214,  214,  214,  214,  214,   62,  214,
      214,  214,  214,  214,   68,  214,   70,  214,  214,  214,
      214,   76,  214,  214,   78,  214,  214,  214,  214,  214,
       87,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  100,  214,  214,  214,  105,  106,  214,  214,  214,
      214,  112,  214,  214,  214,  214,  214,  120,  121,  122,
      214,  123,  125,  214,  214,  214,  214,  132,  134,  214,
      214,  214,  214,  214,  214,  214,  143,  214,  214,  146,
      214,  148,  214,  214,  214,  214,  214,  156,  214,  214,
      214,  214,  162,  214,  214,  214,  168,  169,  214,  214,

      214,  214,  214,  214,  176,  180,  181,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  196,  197,  198,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  210,
      214,  214,  214,  216,  217,    0,    0,   25,  214,   35,
      214,   37,  214,  214,  214,   41,  214,  214,   43,   45,
      214,  214,   50,  214,  214,  214,   55,  214,  214,  214,
      214,   63,  214,   65,   66,  214,  214,  214,   72,   74,
      214,   77,  214,  214,  214,   81,  214,  214,   85,   88,
      214,  214,   91,  214,   92,  214,   95,  214,   97,   98,
      214,  101,  214,  214,  214,  214,  214,  110,  214,  214,

      115,  214,  214,  124,  214,  214,  214,  119,  214,  214,
      136,  214,  214,  214,  214,  142,  144,  214,  214,  214,
      150,  214,  214,  214,    0,  214,  214,  214,  214,  214,
      214,  163,  214,  214,  214,  214,  214,  214,  214,  214,
      175,  177,  214,  214,  183,  185,  214,  214,  214,  191,
      214,  214,  214,  214,  214,  214,  202,  203,  214,  214,
      214,  204,  209,  214,  211,  214,  213,   26,   27,  214,
      214,   38,  214,   40,  214,   42,   46,  214,  214,   51,
       52,   54,  214,   57,  214,  214,  214,   67,  214,  214,
       75,  214,   79,   83,  214,   84,   86,  214,  214,   93,

      214,   96,  214,  214,  214,  108,  214,  214,  111,  113,
      214,  116,  214,  214,  214,  214,  214,  133,  214,  139,
      140,  141,  145,  214,  149,  214,  214,  214,  214,  219,
      214,  214,  214,  160,  214,  214,  214,  214,  214,  172,
      214,  214,  214,  214,  214,  186,  187,  188,  214,  192,
      194,  214,  214,  214,  206,  207,  205,  214,  214,  214,
      214,   39,   44,   47,   48,  214,  214,   58,  214,   61,
       64,  214,  214,   80,   82,  214,   90,  214,   99,  214,
      104,  214,  214,  114,  117,  214,  214,  214,  214,  131,
      138,  214,  214,  152,  153,  155,  157,  214,  159,  161,

      165,  166,  167,  170,  171,  214,  174,  178,  214,  214,
      214,  195,  214,  214,  201,  214,  212,   33,  214,  214,
      214,  214,   69,   71,  214,   94,  214,  107,  214,  118,
      214,  214,  214,  214,  214,  214,  158,  214,  179,  214,
      184,  214,  214,  214,  208,  214,  214,   59,   60,   89,
      214,  109,  214,  214,  214,  147,  214,  214,  173,  214,
      214,  214,  200,  214,   56,  214,  214,  126,  214,  151,
      154,  182,  190,  199,   36,  102,  214,  130,  128,  129,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    1,    8,    9,
       10,   11,   12,   13,   14,    1,   15,   16,   17,   18,
       19,   16,   16,   20,   16,   21,   16,   22,   23,   24,
       25,   26,    1,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   36,   36,   36,   36,

       36,   36,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   60,   59,   59,   59,   59,   59,
       59,   59,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    3,    4,    5,    5
    } ;

static const flex_int16_t yy_base[687] =
    {   0,
        0,    0,  824,  825,  821,   58,   60,   60,  825,  825,
      762,  825,  825,  825,  809,  825,  806,  825,   50,   56,
       62,   68,  825,  825,   65,  794,  793,   64,   80,  105,
       71,   79,   96,  120,  124,   93,    0,  135,  140,   62,
      110,  147,  162,  175,  184,   55,  165,  189,  130,   74,
      825,  810,  825,  825,  802,  813,  176,  123,  825,  811,
      180,  195,  825,  825,  218,  224,  230,  778,  825,  825,
      825,  825,    0,  767,  781,  100,  781,    0,  128,  776,
      762,  126,  763,  765,  759,  766,  762,  762,  757,   68,
      759,  175,  764,  756,  200,  210,  231,  156,  213,  756,

      757,  750,  111,  763,  222,  755,  757,  747,  749,  750,
      747,  223,  159,  749,  751,  739,  168,    0,  744,  236,
      735,  234,  749,  238,  238,  742,  240,  192,    0,  742,
      729,  231,  746,  742,  738,  748,  241,  255,  734,  254,
      256,  729,  253,  262,  739,  741,  721,  725,  256,  728,
      740,  733,  278,  269,  278,  271,  734,  278,    0,  717,
      719,  716,  719,  729,  276,  715,  717,  722,  716,  720,
      281,  710,  718,  708,  720,  712,  718,    0,  312,  825,
      713,  712,  700,    0,  701,    0,  709,    0,  706,  705,
      706,  701,  710,  707,  707,  687,  704,  696,  684,  686,

      724,  292,    0,  682,  698,  122,  686,  694,    0,  686,
      687,  687,  696,  675,    0,  694,    0,  693,  688,  678,
      673,    0,  685,  687,  679,  669,  666,  684,  665,  667,
        0,  669,  676,  678,  675,  657,  662,  283,  284,  656,
      668,    0,  669,  664,  657,    0,    0,  651,  665,  664,
      648,    0,  659,  665,  649,  659,  658,    0,    0,  681,
      649,    0,    0,  645,  639,  638,  644,    0,    0,  634,
      630,  640,  648,  651,  648,  639,    0,  638,  634,    0,
      638,    0,  632,  642,  628,  639,  622,    0,  335,  365,
      620,  632,    0,  620,  366,  633,    0,    0,  619,  622,

      632,  631,  624,  616,  391,    0,    0,  615,  610,  615,
      617,  622,  621,  620,  607,  614,  617,    0,    0,  612,
      600,  607,  598,  613,  362,  596,  607,  610,  593,    0,
      598,  599,  596,    0,  393,  589,  588,  825,  602,    0,
      599,    0,  591,  603,  592,    0,  597,  587,    0,    0,
      586,  295,  825,  581,  578,  592,    0,  587,  577,  576,
      585,    0,  587,    0,    0,  584,  569,  587,    0,    0,
      584,    0,  575,  580,  560,    0,  570,  578,  601,    0,
      569,  579,    0,  577,    0,  570,    0,  563,    0,    0,
      568,    0,  549,  556,  555,  554,  557,  589,  549,  548,

        0,  549,  552,  825,  556,  561,  554,    0,  561,  556,
        0,  553,  541,  545,  549,    0,    0,  536,  535,  534,
      548,  540,  536,  545,  398,  401,  412,  548,  547,  529,
      526,    0,  540,  532,  540,  537,  536,  535,  530,  518,
        0,  825,  523,  521,  522,    0,  515,  514,  514,    0,
      510,  518,  511,  527,  518,  521,    0,    0,  520,  519,
      515,    0,    0,  513,    0,  506,    0,  825,  825,  501,
      501,    0,  502,    0,  499,    0,    0,  498,  510,    0,
        0,    0,  495,  378,  508,  492,  492,    0,  498,  497,
        0,  503,    0,    0,  503,    0,  825,  491,  493,    0,

      495,    0,  483,  487,  496,    0,  481,  495,  825,    0,
      493,  516,  476,  476,  479,  490,  480,    0,  486,    0,
        0,    0,    0,  481,    0,  485,  483,  474,  468,  825,
      465,  481,  469,  501,  467,  468,  459,  474,  473,    0,
      470,  470,  467,  455,  471,    0,    0,    0,  456,    0,
      489,  467,  465,  447,    0,    0,    0,  452,  442,  445,
      448,    0,    0,    0,    0,  453,  460,    0,  441,    0,
        0,  439,  453,    0,    0,  442,    0,  453,    0,  433,
        0,  437,  429,    0,  825,  432,  427,  419,  415,    0,
        0,  414,  407,    0,  418,    0,    0,  421,    0,  825,

        0,    0,    0,    0,    0,  416,    0,  443,  422,  406,
      412,  825,  408,  418,    0,  411,    0,    0,  396,  401,
      399,  395,    0,    0,  397,    0,  392,    0,  393,    0,
      407,  394,  396,  393,  388,  379,    0,  401,  825,  385,
        0,  383,  396,  387,    0,  384,  382,    0,    0,    0,
      394,    0,  379,  375,  377,    0,  375,  368,    0,  287,
      292,  267,    0,  260,    0,  238,  232,    0,  182,    0,
        0,    0,    0,    0,    0,    0,   92,    0,   56,    0,
      825,  461,  466,  469,  472,  476
    } ;

static const flex_int16_t yy_def[687] =
    {   0,
      681,    1,  681,  681,  681,  681,  681,  682,  681,  681,
      683,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      681,  681,  681,  681,  684,  681,  681,  682,  681,  682,
      683,  683,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,

      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  685,  681,  681,
      681,  681,  681,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,

      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  681,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,

      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  685,  681,  681,  681,  681,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  681,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,

      684,  684,  684,  681,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  686,  289,  289,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  681,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  681,  681,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  681,  684,  684,  684,

      684,  684,  684,  684,  684,  684,  684,  684,  681,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  681,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  681,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  681,

      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  681,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  681,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
      684,  684,  684,  684,  684,  684,  684,  684,  684,  684,
        0,  681,  681,  681,  681,  681
    } ;

static const flex_int16_t yy_nxt[886] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   19,   21,   19,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   37,   38,   39,   40,
       41,   42,   37,   43,   44,   45,   46,   47,   48,   49,
       50,   37,   51,   52,   53,   54,    4,    4,   37,   55,
       57,   57,   57,   57,   59,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   66,   65,   65,   65,   67,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   69,
       70,   74,  131,   75,  162,   68,  163,   96,  202,  164,

      680,   97,  132,   76,  176,   98,   79,  101,   77,   78,
       80,   99,  203,   60,   81,  177,  102,   82,  103,  100,
       83,  679,  106,   84,  118,  119,  104,   59,  105,  186,
       85,   86,  120,  107,   87,   88,  108,  224,   89,  109,
      225,  133,   90,   91,  187,   92,  110,  134,   93,  135,
      114,   94,  193,  136,  115,   95,  189,  111,  116,  358,
      112,  121,  359,  113,  117,  122,  125,  190,  126,  123,
      174,  175,  194,  137,  127,  124,   60,  138,   57,   57,
      128,  139,  180,  180,  129,  238,  130,  140,  143,  239,
      141,  165,  144,  142,  217,  166,  145,  180,  180,  167,

      218,  146,  147,  148,  205,  149,  243,  150,  151,  152,
      155,  244,  206,  207,  156,  168,  153,  157,  158,  169,
      154,  263,  170,  171,  159,  678,  210,  160,  211,  172,
      161,  264,  173,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,  181,  219,  212,   62,  213,  227,  182,  214,  215,
      235,  220,  216,  228,  246,  251,  254,  236,  237,  260,
      257,  677,  247,  252,  267,  676,  268,  261,  255,  262,
      248,  275,  273,  249,  274,  276,  256,  258,  279,  675,
      283,  288,  286,  296,  277,  280,  284,  287,  281,  304,

      289,  297,  282,  290,  301,  306,  311,  291,  302,  308,
      326,  674,  305,  319,  388,  312,  313,  307,  354,  320,
      309,  303,  673,  355,  386,  478,  327,  335,  335,  335,
      335,  335,  335,  387,  389,  425,  425,  672,  479,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      426,  426,  426,  426,  426,  426,  425,  425,  425,  425,
      425,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  425,  425,  425,
      425,  426,  425,  426,  427,  428,  433,  442,  671,  459,

      530,  530,  429,  530,  530,  670,  434,  460,  335,  335,
      335,  335,  335,  335,  530,  530,  567,  669,  668,  667,
      666,  665,  568,  664,  663,  443,  662,  661,  660,  659,
      658,  657,  656,  655,  654,  653,  652,  651,  650,  649,
      648,  647,  646,  645,  644,  643,  642,  641,  640,  639,
      638,  637,  636,  635,  634,  633,  632,  631,  630,  629,
      426,   58,   58,   58,   58,   58,   61,  628,   61,   61,
       61,   73,  627,   73,  334,  334,  425,  425,  425,  425,
      425,  626,  625,  624,  623,  622,  621,  620,  619,  618,
      617,  616,  615,  614,  613,  612,  611,  610,  609,  608,

      607,  606,  605,  604,  603,  602,  601,  600,  599,  598,
      597,  596,  595,  594,  593,  592,  591,  590,  589,  588,
      587,  586,  585,  584,  583,  582,  581,  580,  579,  578,
      577,  576,  575,  574,  573,  572,  571,  570,  569,  566,
      565,  564,  563,  562,  561,  560,  559,  558,  557,  556,
      555,  554,  553,  552,  551,  550,  549,  548,  547,  546,
      545,  544,  543,  542,  541,  540,  539,  538,  537,  536,
      535,  534,  533,  532,  531,  529,  528,  527,  526,  525,
      524,  523,  522,  521,  520,  519,  518,  517,  516,  515,
      514,  513,  512,  511,  510,  509,  508,  507,  506,  505,

      504,  503,  502,  501,  500,  499,  498,  497,  496,  495,
      494,  493,  492,  491,  490,  489,  488,  487,  486,  485,
      484,  483,  482,  481,  480,  477,  476,  475,  474,  473,
      472,  471,  470,  469,  468,  467,  466,  465,  464,  463,
      462,  461,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  441,  440,  439,
      438,  437,  436,  435,  432,  431,  430,  424,  423,  422,
      421,  420,  419,  418,  417,  416,  415,  414,  413,  412,
      411,  410,  409,  408,  407,  406,  405,  404,  403,  402,
      401,  400,  399,  398,  397,  396,  395,  394,  393,  392,

      391,  390,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  357,  356,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  333,  332,
      331,  330,  329,  328,  325,  324,  323,  322,  321,  318,
      317,  316,  315,  314,  310,  300,  299,  298,  295,  294,
      293,  292,  285,  278,  272,  271,  270,  269,  266,  265,
      259,  253,  250,  245,  242,  241,  240,  234,  233,  232,
      231,  230,  229,  226,  223,  222,  221,  209,  208,  204,

      201,  200,  199,  198,  197,  196,  195,  192,  191,  188,
      185,  184,  183,  681,   56,  179,  178,   72,   71,   64,
       63,   62,   56,  681,    3,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681
    } ;

static const flex_int16_t yy_chk[886] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        6,    6,    7,    7,    8,   19,   19,   19,   19,   19,
       19,   20,   20,   20,   20,   20,   20,   21,   21,   21,
       21,   21,   21,   22,   22,   22,   22,   22,   22,   25,
       25,   28,   40,   28,   46,   22,   46,   31,   90,   46,

      679,   31,   40,   28,   50,   31,   29,   32,   28,   28,
       29,   31,   90,    8,   29,   50,   32,   29,   32,   31,
       29,  677,   33,   29,   36,   36,   32,   58,   32,   76,
       29,   30,   36,   33,   30,   30,   33,  103,   30,   33,
      103,   41,   30,   30,   76,   30,   34,   41,   30,   41,
       35,   30,   82,   41,   35,   30,   79,   34,   35,  206,
       34,   38,  206,   34,   35,   38,   39,   79,   39,   38,
       49,   49,   82,   42,   39,   38,   58,   42,   57,   57,
       39,   42,   61,   61,   39,  113,   39,   42,   43,  113,
       42,   47,   43,   42,   98,   47,   43,   62,   62,   47,

       98,   43,   43,   44,   92,   44,  117,   44,   44,   44,
       45,  117,   92,   92,   45,   48,   44,   45,   45,   48,
       44,  128,   48,   48,   45,  669,   95,   45,   95,   48,
       45,  128,   48,   65,   65,   65,   65,   65,   65,   66,
       66,   66,   66,   66,   66,   67,   67,   67,   67,   67,
       67,   66,   99,   96,   62,   96,  105,   67,   97,   97,
      112,   99,   97,  105,  120,  122,  124,  112,  112,  127,
      125,  667,  120,  122,  132,  666,  132,  127,  124,  127,
      120,  138,  137,  120,  137,  138,  124,  125,  140,  664,
      141,  144,  143,  149,  138,  140,  141,  143,  140,  154,

      144,  149,  140,  144,  153,  155,  158,  144,  153,  156,
      171,  662,  154,  165,  239,  158,  158,  155,  202,  165,
      156,  153,  661,  202,  238,  352,  171,  179,  179,  179,
      179,  179,  179,  238,  239,  289,  289,  660,  352,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  290,  295,  305,  658,  325,

      425,  425,  290,  426,  426,  657,  295,  325,  335,  335,
      335,  335,  335,  335,  427,  427,  484,  655,  654,  653,
      651,  647,  484,  646,  644,  305,  643,  642,  640,  638,
      636,  635,  634,  633,  632,  631,  629,  627,  625,  622,
      621,  620,  619,  616,  614,  613,  611,  610,  609,  608,
      606,  598,  595,  593,  592,  589,  588,  587,  586,  583,
      426,  682,  682,  682,  682,  682,  683,  582,  683,  683,
      683,  684,  580,  684,  685,  685,  686,  686,  686,  686,
      686,  578,  576,  573,  572,  569,  567,  566,  561,  560,
      559,  558,  554,  553,  552,  551,  549,  545,  544,  543,

      542,  541,  539,  538,  537,  536,  535,  534,  533,  532,
      531,  529,  528,  527,  526,  524,  519,  517,  516,  515,
      514,  513,  512,  511,  508,  507,  505,  504,  503,  501,
      499,  498,  495,  492,  490,  489,  487,  486,  485,  483,
      479,  478,  475,  473,  471,  470,  466,  464,  461,  460,
      459,  456,  455,  454,  453,  452,  451,  449,  448,  447,
      445,  444,  443,  440,  439,  438,  437,  436,  435,  434,
      433,  431,  430,  429,  428,  424,  423,  422,  421,  420,
      419,  418,  415,  414,  413,  412,  410,  409,  407,  406,
      405,  403,  402,  400,  399,  398,  397,  396,  395,  394,

      393,  391,  388,  386,  384,  382,  381,  379,  378,  377,
      375,  374,  373,  371,  368,  367,  366,  363,  361,  360,
      359,  358,  356,  355,  354,  351,  348,  347,  345,  344,
      343,  341,  339,  337,  336,  333,  332,  331,  329,  328,
      327,  326,  324,  323,  322,  321,  320,  317,  316,  315,
      314,  313,  312,  311,  310,  309,  308,  304,  303,  302,
      301,  300,  299,  296,  294,  292,  291,  287,  286,  285,
      284,  283,  281,  279,  278,  276,  275,  274,  273,  272,
      271,  270,  267,  266,  265,  264,  261,  260,  257,  256,
      255,  254,  253,  251,  250,  249,  248,  245,  244,  243,

      241,  240,  237,  236,  235,  234,  233,  232,  230,  229,
      228,  227,  226,  225,  224,  223,  221,  220,  219,  218,
      216,  214,  213,  212,  211,  210,  208,  207,  205,  204,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  187,  185,  183,  182,  181,  177,  176,
      175,  174,  173,  172,  170,  169,  168,  167,  166,  164,
      163,  162,  161,  160,  157,  152,  151,  150,  148,  147,
      146,  145,  142,  139,  136,  135,  134,  133,  131,  130,
      126,  123,  121,  119,  116,  115,  114,  111,  110,  109,
      108,  107,  106,  104,  102,  101,  100,   94,   93,   91,

       89,   88,   87,   86,   85,   84,   83,   81,   80,   77,
       75,   74,   68,   60,   56,   55,   52,   27,   26,   17,
       15,   11,    5,    3,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681,  681,  681,  681,  681,  681,
      681,  681,  681,  681,  681
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[224] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 
    1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/ugbc.lex"
#line 2 "src/ugbc.lex"

#include <string.h>
#include "ugbc.tab.h" /* The tokens */
#line 900 "src-generated/ugbc.yy.c"
#line 901 "src-generated/ugbc.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 9 "src/ugbc.lex"


#line 1121 "src-generated/ugbc.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 682 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 825 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 11 "src/ugbc.lex"
{ return(NewLine);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 12 "src/ugbc.lex"
{ return(SEMICOLON); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 13 "src/ugbc.lex"
{ return(COLON); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 14 "src/ugbc.lex"
{ return(OP); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 15 "src/ugbc.lex"
{ return(CP); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 16 "src/ugbc.lex"
{ return(COMMA); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 17 "src/ugbc.lex"
{ return(ASSIGN); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 18 "src/ugbc.lex"
{ return(EQUAL); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 19 "src/ugbc.lex"
{ return(PLUS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 20 "src/ugbc.lex"
{ return(MINUS); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 21 "src/ugbc.lex"
{ return(INC); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 22 "src/ugbc.lex"
{ return(DEC); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 23 "src/ugbc.lex"
{ return(HASH); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 24 "src/ugbc.lex"
{ return(LT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 25 "src/ugbc.lex"
{ return(LTE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 26 "src/ugbc.lex"
{ return(GT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 27 "src/ugbc.lex"
{ return(GTE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "src/ugbc.lex"
{ return(DISEQUAL); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 "src/ugbc.lex"
{ return(MULTIPLICATION); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 30 "src/ugbc.lex"
{ return(DOLLAR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 31 "src/ugbc.lex"
{ return(POW); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 32 "src/ugbc.lex"
{ return(DIVISION); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 33 "src/ugbc.lex"
{ return(OSP); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 34 "src/ugbc.lex"
{ return(CSP); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 36 "src/ugbc.lex"
{ return (BYTE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 37 "src/ugbc.lex"
{ return (WORD); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 38 "src/ugbc.lex"
{ return (DWORD); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 40 "src/ugbc.lex"
{ return (ABS); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 41 "src/ugbc.lex"
{ return (AS); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 42 "src/ugbc.lex"
{ return (ASC); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 43 "src/ugbc.lex"
{ return (AT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 44 "src/ugbc.lex"
{ return (ADD); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 45 "src/ugbc.lex"
{ return (ADDRESS); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 46 "src/ugbc.lex"
{ return (AND); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 47 "src/ugbc.lex"
{ return (ANSI); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 48 "src/ugbc.lex"
{ return (BACKGROUND); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 49 "src/ugbc.lex"
{ return (BANK); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 50 "src/ugbc.lex"
{ return (BEG); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 51 "src/ugbc.lex"
{ return (BITMAP); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 52 "src/ugbc.lex"
{ return (BLACK); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 53 "src/ugbc.lex"
{ return (BLUE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 54 "src/ugbc.lex"
{ return(BROWN); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 55 "src/ugbc.lex"
{ return (BYTE); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 56 "src/ugbc.lex"
{ return (BORDER); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 57 "src/ugbc.lex"
{ return (CALL); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 58 "src/ugbc.lex"
{ return (CDOWN); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 59 "src/ugbc.lex"
{ return (CENTER); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 60 "src/ugbc.lex"
{ return (CENTRE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 61 "src/ugbc.lex"
{ return (CHR); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 62 "src/ugbc.lex"
{ return (CHR); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 63 "src/ugbc.lex"
{ return (CLEAR); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 64 "src/ugbc.lex"
{ return (CLEFT); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 65 "src/ugbc.lex"
{ return (CLS); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 66 "src/ugbc.lex"
{ return (CMOVE); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 67 "src/ugbc.lex"
{ return (CODE); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 68 "src/ugbc.lex"
{ return (COLLISION); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 69 "src/ugbc.lex"
{ return (COLOR); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 70 "src/ugbc.lex"
{ return (COLORS); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 71 "src/ugbc.lex"
{ return (COLORMAP); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 72 "src/ugbc.lex"
{ return (COMPRESS); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 73 "src/ugbc.lex"
{ return (CRIGHT); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 74 "src/ugbc.lex"
{ return (CUP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 75 "src/ugbc.lex"
{ return(CYAN); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 76 "src/ugbc.lex"
{ return (CYCLES); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 77 "src/ugbc.lex"
{ return(DARK); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 78 "src/ugbc.lex"
{ return (DATA); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 79 "src/ugbc.lex"
{ return (DEBUG); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 80 "src/ugbc.lex"
{ return (DEC); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 81 "src/ugbc.lex"
{ return (DEFAULT); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 82 "src/ugbc.lex"
{ return (DIM); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 83 "src/ugbc.lex"
{ return (DISABLE); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 84 "src/ugbc.lex"
{ return (DONE); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 85 "src/ugbc.lex"
{ return (DO); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 86 "src/ugbc.lex"
{ return (DOWN); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 87 "src/ugbc.lex"
{ return (DWORD); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 88 "src/ugbc.lex"
{ return(ECM); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 89 "src/ugbc.lex"
{ return(ELSE); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 90 "src/ugbc.lex"
{ return (END); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 91 "src/ugbc.lex"
{ return (ENDIF); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 92 "src/ugbc.lex"
{ return (ENABLE); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 93 "src/ugbc.lex"
{ return (EXIT); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 94 "src/ugbc.lex"
{ return (EXPAND); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 95 "src/ugbc.lex"
{ return (EVERY); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 96 "src/ugbc.lex"
{ return(FALSE); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 97 "src/ugbc.lex"
{ return(FLIP); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 98 "src/ugbc.lex"
{ return(FLIP); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 99 "src/ugbc.lex"
{ return(FOR); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 100 "src/ugbc.lex"
{ return (FROM); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 101 "src/ugbc.lex"
{ return (GAMELOOP); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 102 "src/ugbc.lex"
{ return (GLOBAL); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 103 "src/ugbc.lex"
{ return(GOLD); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 104 "src/ugbc.lex"
{ return (GOTO); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 105 "src/ugbc.lex"
{ return (GOSUB); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 106 "src/ugbc.lex"
{ return (GRAPHIC); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 107 "src/ugbc.lex"
{ return(GRAY); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 108 "src/ugbc.lex"
{ return(GREEN); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 109 "src/ugbc.lex"
{ return(GREY); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 110 "src/ugbc.lex"
{ return (HALT); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 111 "src/ugbc.lex"
{ return (HEIGHT); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 112 "src/ugbc.lex"
{ return (HIT); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 113 "src/ugbc.lex"
{ return (HOME); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 114 "src/ugbc.lex"
{ return (HORIZONTAL); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 115 "src/ugbc.lex"
{ return (IF); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 116 "src/ugbc.lex"
{ return (IGNORE); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 117 "src/ugbc.lex"
{ return (INC); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 118 "src/ugbc.lex"
{ return (INK); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 119 "src/ugbc.lex"
{ return (INVERSE); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 120 "src/ugbc.lex"
{ return (INSTR); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 121 "src/ugbc.lex"
{ return(LAVENDER); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 122 "src/ugbc.lex"
{ return (LEFT); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 123 "src/ugbc.lex"
{ return (LEFT); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 124 "src/ugbc.lex"
{ return (LEN); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 125 "src/ugbc.lex"
{ return(LIGHT); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 126 "src/ugbc.lex"
{ return(LOCATE); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 127 "src/ugbc.lex"
{ return (LOOP); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 128 "src/ugbc.lex"
{ return (LOWER); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 129 "src/ugbc.lex"
{ return (LOWER); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 130 "src/ugbc.lex"
{ return(MAGENTA); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 131 "src/ugbc.lex"
{ return (NEXT); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 132 "src/ugbc.lex"
{ return(MAX); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 133 "src/ugbc.lex"
{ return(MCM); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 134 "src/ugbc.lex"
{ return(MID); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 135 "src/ugbc.lex"
{ return(MIN); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 136 "src/ugbc.lex"
{ return(MID); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 137 "src/ugbc.lex"
{ return(MOD); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 138 "src/ugbc.lex"
{ return(MONOCOLOR); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 139 "src/ugbc.lex"
{ return (MILLISECOND); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 140 "src/ugbc.lex"
{ return (MILLISECOND); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 141 "src/ugbc.lex"
{ return (MILLISECONDS); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 142 "src/ugbc.lex"
{ return(MULTICOLOR); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 143 "src/ugbc.lex"
{ return(NORMAL); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 144 "src/ugbc.lex"
{ return(NOT); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 145 "src/ugbc.lex"
{ return(OLIVE); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 146 "src/ugbc.lex"
{ return (OFF); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 147 "src/ugbc.lex"
{ return (ON); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 148 "src/ugbc.lex"
{ return (ONLY); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 149 "src/ugbc.lex"
{ return (OR); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 150 "src/ugbc.lex"
{ return(ORANGE); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 151 "src/ugbc.lex"
{ return(PAPER); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 152 "src/ugbc.lex"
{ return(PARAM); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 153 "src/ugbc.lex"
{ return(PEACH); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 154 "src/ugbc.lex"
{ return (PEEK); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 155 "src/ugbc.lex"
{ return (PEN); }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 156 "src/ugbc.lex"
{ return(PINK); }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 157 "src/ugbc.lex"
{ return (POINT); }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 158 "src/ugbc.lex"
{ return (POP); }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 159 "src/ugbc.lex"
{ return (POSITION); }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 160 "src/ugbc.lex"
{ return (POWERING); }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 161 "src/ugbc.lex"
{ return (PRINT); }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 162 "src/ugbc.lex"
{ return (PROC); }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 163 "src/ugbc.lex"
{ return (PROCEDURE); }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 164 "src/ugbc.lex"
{ return(PURPLE); }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 165 "src/ugbc.lex"
{ return (RANDOM); }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 166 "src/ugbc.lex"
{ return (RANDOMIZE); }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 167 "src/ugbc.lex"
{ return (RASTER); }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 168 "src/ugbc.lex"
{ return(RED); }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 169 "src/ugbc.lex"
{ return (REPEAT); }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 170 "src/ugbc.lex"
{ return (REPLACE); }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 171 "src/ugbc.lex"
{ return (RETURN); }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 172 "src/ugbc.lex"
{ return (RIGHT); }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 173 "src/ugbc.lex"
{ return (RIGHT); }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 174 "src/ugbc.lex"
{ return (RND); }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 175 "src/ugbc.lex"
{ return (ROWS); }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 176 "src/ugbc.lex"
{ return (S); }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 177 "src/ugbc.lex"
{ return (SCREEN); }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 178 "src/ugbc.lex"
{ return (SCROLL); }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 179 "src/ugbc.lex"
{ return (SELECT); }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 180 "src/ugbc.lex"
{ return (SET); }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 181 "src/ugbc.lex"
{ return (SGN); }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 182 "src/ugbc.lex"
{ return (SHARED); }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 183 "src/ugbc.lex"
{ return (SIGNED); }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 184 "src/ugbc.lex"
{ return (SPACE); }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 185 "src/ugbc.lex"
{ return (SPECIFIC); }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 186 "src/ugbc.lex"
{ return (SPRITE); }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 187 "src/ugbc.lex"
{ return (STEP); }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 188 "src/ugbc.lex"
{ return (STR); }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 189 "src/ugbc.lex"
{ return (STR); }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 190 "src/ugbc.lex"
{ return (STRING); }
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 191 "src/ugbc.lex"
{ return (STRING); }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 192 "src/ugbc.lex"
{ return(TAB); }
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 193 "src/ugbc.lex"
{ return(TAN); }
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 194 "src/ugbc.lex"
{ return (TEMPORARY); }
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 195 "src/ugbc.lex"
{ return (TEXT); }
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 196 "src/ugbc.lex"
{ return (TEXTMAP); }
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 197 "src/ugbc.lex"
{ return (THEN); }
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 198 "src/ugbc.lex"
{ return (TICKS); }
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 199 "src/ugbc.lex"
{ return (TILES); }
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 200 "src/ugbc.lex"
{ return (TIMER); }
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 201 "src/ugbc.lex"
{ return (TO); }
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 202 "src/ugbc.lex"
{ return(TURQUOISE); }
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 203 "src/ugbc.lex"
{ return(TRUE); }
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 204 "src/ugbc.lex"
{ return (UNTIL); }
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 205 "src/ugbc.lex"
{ return (UP); }
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 206 "src/ugbc.lex"
{ return (UPPER); }
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 207 "src/ugbc.lex"
{ return (UPPER); }
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 208 "src/ugbc.lex"
{ return (USE); }
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 209 "src/ugbc.lex"
{ return (VAL); }
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 210 "src/ugbc.lex"
{ return (VAR); }
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 211 "src/ugbc.lex"
{ return (VARIABLES); }
	YY_BREAK
case 200:
YY_RULE_SETUP
#line 212 "src/ugbc.lex"
{ return (VERTICAL); }
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 213 "src/ugbc.lex"
{ return(VIOLET); }
	YY_BREAK
case 202:
YY_RULE_SETUP
#line 214 "src/ugbc.lex"
{ return (WAIT); }
	YY_BREAK
case 203:
YY_RULE_SETUP
#line 215 "src/ugbc.lex"
{ return (WEND); }
	YY_BREAK
case 204:
YY_RULE_SETUP
#line 216 "src/ugbc.lex"
{ return (WITH); }
	YY_BREAK
case 205:
YY_RULE_SETUP
#line 217 "src/ugbc.lex"
{ return (WIDTH); }
	YY_BREAK
case 206:
YY_RULE_SETUP
#line 218 "src/ugbc.lex"
{ return (WHILE); }
	YY_BREAK
case 207:
YY_RULE_SETUP
#line 219 "src/ugbc.lex"
{ return(WHITE); }
	YY_BREAK
case 208:
YY_RULE_SETUP
#line 220 "src/ugbc.lex"
{ return(WRITING); }
	YY_BREAK
case 209:
YY_RULE_SETUP
#line 221 "src/ugbc.lex"
{ return (WORD); }
	YY_BREAK
case 210:
YY_RULE_SETUP
#line 222 "src/ugbc.lex"
{ return (XOR); }
	YY_BREAK
case 211:
YY_RULE_SETUP
#line 223 "src/ugbc.lex"
{ return (XPEN); }
	YY_BREAK
case 212:
YY_RULE_SETUP
#line 224 "src/ugbc.lex"
{ return(YELLOW); }
	YY_BREAK
case 213:
YY_RULE_SETUP
#line 225 "src/ugbc.lex"
{ return (YPEN); }
	YY_BREAK
case 214:
YY_RULE_SETUP
#line 227 "src/ugbc.lex"
{ yylval.string = strdup(yytext); return(Identifier);  }
	YY_BREAK
case 215:
/* rule 215 can match eol */
YY_RULE_SETUP
#line 228 "src/ugbc.lex"
{ yylval.string = strdup(yytext); memcpy(yylval.string,yylval.string+1,strlen(yylval.string)); yylval.string[strlen(yylval.string)-1]=0; return(String);  }
	YY_BREAK
case 216:
YY_RULE_SETUP
#line 229 "src/ugbc.lex"
{ yylval.integer = strtol(yytext+1,0,16); return(Integer); }
	YY_BREAK
case 217:
YY_RULE_SETUP
#line 230 "src/ugbc.lex"
{ yylval.integer = atoi(yytext); return(Integer);  }
	YY_BREAK
case 218:
YY_RULE_SETUP
#line 231 "src/ugbc.lex"
{ yylval.integer = atoi(yytext); return(Integer);  }
	YY_BREAK
case 219:
/* rule 219 can match eol */
YY_RULE_SETUP
#line 232 "src/ugbc.lex"
{ return(Remark);  }
	YY_BREAK
case 220:
/* rule 220 can match eol */
YY_RULE_SETUP
#line 233 "src/ugbc.lex"
{ return(Remark);  }
	YY_BREAK
case 221:
YY_RULE_SETUP
#line 235 "src/ugbc.lex"

	YY_BREAK
case 222:
YY_RULE_SETUP
#line 236 "src/ugbc.lex"
{ return(yytext[0]); }
	YY_BREAK
case 223:
YY_RULE_SETUP
#line 238 "src/ugbc.lex"
ECHO;
	YY_BREAK
#line 2307 "src-generated/ugbc.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 682 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 682 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 681);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 238 "src/ugbc.lex"


