#line 2 "src-generated/ugbc.yy.c"

#line 4 "src-generated/ugbc.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 165
#define YY_END_OF_BUFFER 166
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[528] =
    {   0,
        0,    0,  166,  164,  163,    1,    1,  164,   13,   20,
      164,    4,    5,   19,    9,    6,   10,  160,  160,  160,
      160,    3,    2,   14,    7,   16,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  117,  157,  157,  157,  157,  157,  157,  163,
        1,    0,  158,    0,  159,    0,    0,   11,   12,  160,
      160,  160,    0,   15,   18,    8,   17,  157,  157,   24,
       25,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,   49,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,

      157,   75,  157,  157,  157,  157,  157,  157,  157,  157,
      157,   90,  157,  157,  157,  157,  157,   97,   98,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  135,  157,  157,  157,  139,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  162,    0,    0,    0,   26,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,   52,  157,
      157,   54,  157,  157,  157,  157,   61,  157,  157,  157,
      157,  157,  157,  157,  157,  157,   73,  157,  157,  157,

      157,  157,  157,  157,  157,   86,   87,  157,  157,  157,
      157,   94,   96,  157,  157,  157,  157,  102,  157,  157,
      105,  157,  157,  157,  157,  111,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  124,  128,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  142,  143,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
        0,    0,   21,  157,   28,  157,  157,  157,   32,  157,
      157,   34,  157,   37,  157,  157,  157,   42,  157,   44,
       45,  157,  157,   48,   50,  157,   53,  157,  157,  157,
       57,  157,  157,   62,  157,   64,  157,   65,  157,   68,

      157,   70,   71,  157,  157,  157,  157,   78,  157,   81,
      157,  157,   88,  157,  157,  157,   85,  157,  157,  157,
      101,  103,  157,  157,  157,  157,  157,    0,  157,  157,
      157,  157,  157,  116,  157,  157,  157,  157,  157,  123,
      125,  157,  157,  130,  132,  157,  157,  137,  157,  157,
      157,  157,  157,  157,  147,  148,  157,  157,  157,  149,
      153,  154,  157,  156,   22,   23,  157,   29,  157,   31,
      157,   33,   36,  157,   39,  157,  157,   46,  157,   51,
      157,   55,   59,  157,   60,  157,   66,  157,   69,  157,
      157,   76,  157,   79,   80,   82,  157,  157,  157,  157,

       95,  157,  100,  104,  157,  157,  157,  157,  161,  157,
      157,  114,  157,  157,  157,  121,  157,  157,  157,  157,
      133,  134,  157,  138,  140,  157,  157,  157,  151,  152,
      150,  157,  157,   30,   35,  157,  157,  157,   43,  157,
       56,   58,  157,  157,   72,  157,  157,   83,  157,  157,
      157,  157,   99,  157,  107,  108,  110,  112,  113,  115,
      118,  119,  120,  122,  126,  157,  157,  157,  141,  157,
      157,  146,  155,  157,  157,  157,  157,   47,  157,   67,
      157,  157,   84,  157,  157,  157,  157,  157,  127,  157,
      131,  157,  157,  157,  157,  157,   40,   41,   63,  157,

       77,  157,  157,  157,  106,  157,  157,  157,  157,  145,
      157,   38,  157,  157,   89,  157,  109,  129,  136,  144,
       27,   74,  157,   93,   91,   92,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    1,    8,    9,
       10,   11,   12,   13,   14,    1,    1,   15,   16,   17,
       18,   15,   15,   19,   15,   20,   15,   21,   22,   23,
       24,   25,    1,    1,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   52,   52,   54,   52,   35,   35,   35,   35,

       35,   35,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   56,   55,   55,   55,   55,   55,
       55,   55,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    4,    4,    3,    5,    5
    } ;

static const flex_int16_t yy_base[534] =
    {   0,
        0,    0,  644,  645,  641,   54,   56,   56,  645,    0,
      586,  645,  645,  645,  629,  645,  626,   47,   53,   59,
       65,  645,  645,   62,  615,  614,   49,   65,   60,   77,
       84,   87,   92,   94,   59,    0,  110,  111,   66,  110,
      108,  126,  131,  137,   75,  139,  148,  596,  134,  634,
      181,  138,  645,  632,    0,  183,  186,  645,  645,  177,
      183,  189,  600,  645,  645,  645,  645,    0,  604,    0,
        0,  140,  600,  586,  100,  587,  589,  583,  597,  182,
      186,  170,  599,  581,  178,  584,  585,  578,   75,  591,
       88,  583,  576,  578,  579,  184,  132,  579,  581,  569,

      570,    0,  568,  564,  579,  577,  182,  576,  569,  194,
      567,    0,  568,  555,  558,  571,  567,    0,  574,  206,
      560,  193,  555,  194,  206,  565,  548,  552,  557,  198,
      209,  554,  205,  562,  212,    0,  545,  547,  544,  547,
      213,  544,  546,  551,  545,  549,  217,  539,  551,  543,
      549,  645,  544,  543,  531,    0,  539,  538,  539,  534,
      543,  540,  540,  520,  537,  540,  535,  218,  523,  524,
      525,  525,  534,  513,  532,  527,  517,  512,    0,  524,
      526,  518,  508,  505,  523,  504,    0,  509,  516,  516,
      498,  503,  207,  223,  497,  509,    0,  506,  494,  508,

      492,  503,  494,  504,  503,    0,  525,  494,  490,  484,
      483,    0,    0,  480,  487,  497,  488,    0,  487,  483,
        0,  487,  479,  490,  473,    0,  273,  487,  470,  482,
      470,  229,  483,  484,  477,  469,  254,    0,  468,  463,
      468,  470,  475,  474,  461,  468,  471,    0,  466,  454,
      461,  452,  467,  223,  450,  461,  464,  453,  454,  451,
      444,  443,  645,  455,    0,  447,  459,  448,    0,  453,
      443,    0,  438,    0,  446,  436,  435,    0,  447,    0,
        0,  444,  448,    0,    0,  445,    0,  436,  441,  421,
        0,  431,  439,    0,  431,    0,  440,    0,  433,    0,

      426,    0,    0,  431,  412,  419,  422,  453,  414,    0,
      415,  418,  645,  422,  427,  420,    0,  423,  420,  418,
        0,    0,  405,  404,  411,  407,  416,  260,  329,  389,
      418,  400,  397,    0,  411,  403,  411,  408,  392,    0,
      645,  397,  395,  396,    0,  389,  388,    0,  385,  393,
      386,  402,  393,  396,    0,    0,  395,  394,  390,    0,
        0,    0,  382,    0,  645,  645,  378,    0,  379,    0,
      376,    0,    0,  374,  379,  386,  371,    0,  377,    0,
      383,    0,    0,  383,    0,  371,    0,  376,    0,  364,
      368,    0,  370,  645,    0,  389,  346,  336,  339,  350,

        0,  347,    0,    0,  342,  345,  336,  330,  645,  327,
      332,  363,  330,  331,  322,    0,  336,  333,  321,  337,
        0,    0,  322,    0,  354,  333,  331,  313,    0,    0,
        0,  309,  316,    0,    0,  321,  323,  304,    0,  317,
        0,    0,  306,  317,    0,  305,  298,  645,  301,  294,
      286,  282,    0,  281,    0,  286,    0,    0,    0,  645,
        0,    0,    0,    0,  312,  292,  276,  282,  645,  278,
      288,    0,    0,  267,  272,  270,  266,    0,  268,    0,
      263,  264,    0,  278,  265,  267,  264,  251,  645,  258,
        0,  256,  269,  256,  253,  252,    0,    0,    0,  264,

        0,  249,  234,  236,    0,  242,  221,  240,  223,    0,
      237,    0,  228,  186,    0,  175,    0,    0,    0,    0,
        0,    0,   90,    0,   45,    0,  645,  382,  385,  389,
      392,  397,  402
    } ;

static const flex_int16_t yy_def[534] =
    {   0,
      527,    1,  527,  527,  527,  527,  527,  528,  527,  529,
      530,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  527,
      527,  528,  527,  528,  529,  530,  530,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  527,  527,  527,  527,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  532,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      527,  527,  527,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  527,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  533,  532,  329,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      527,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  527,  527,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  527,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  527,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  527,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  527,
      531,  531,  531,  531,  531,  531,  531,  531,  527,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  527,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,    0,  527,  527,  527,
      527,  527,  527
    } ;

static const flex_int16_t yy_nxt[702] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   18,   20,   18,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   36,   37,   38,   39,   40,
       41,   36,   42,   43,   44,   45,   46,   47,   48,   49,
       36,    4,    4,    4,   36,   36,   51,   51,   51,   51,
       53,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   61,   60,   60,   60,   62,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   64,   65,   69,  526,  102,
       72,   63,   70,   71,   73,  114,   79,  103,   74,   80,

      181,   75,   82,  182,   76,  115,   83,   77,   54,   81,
       84,   87,   92,  139,   78,  140,   85,   95,  525,   98,
       88,  184,   89,   99,   86,  161,   93,  100,  185,   94,
       90,   96,   91,  101,   97,  104,  108,  120,  109,  105,
      116,  121,   53,  106,  110,  162,  117,  122,  118,  107,
      111,  124,  119,  123,  112,  125,  113,  193,  128,  126,
      129,  194,  132,  150,  141,  127,  133,  157,  142,  134,
      135,  130,  143,  144,  151,  131,  136,  145,  158,  137,
      146,  147,  138,   51,   51,  152,  152,  148,  152,  152,
       54,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   60,   60,   60,   60,   60,  153,
      167,  170,  172,  171,  173,  154,  176,  524,  168,  169,
      190,  203,  207,  234,  523,  177,  220,  191,  192,  204,
      208,  216,  224,  221,  226,  217,  222,  225,  236,  242,
      235,   57,  239,  227,  218,  255,  228,  299,  243,  248,
      229,  237,  301,  240,  275,  249,  300,  276,  335,  357,
      341,  256,  409,  409,  522,  521,  520,  358,  336,  519,
      518,  517,  302,  328,  328,  516,  515,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  342,  514,  513,
      512,  511,  510,  328,  328,  328,  328,  328,  509,  508,

      507,  506,  505,  504,  503,  502,  501,  500,  499,  498,
      497,  496,  495,  494,  493,  492,  491,  490,  489,  488,
      487,  486,  485,  484,  328,  328,  483,  482,  330,  328,
      328,  409,  409,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  481,  480,  479,  478,  477,  476,  328,
      328,  328,  328,  328,  475,  474,  473,  472,  471,  470,
      469,  468,  467,  466,  465,  464,  463,  462,  461,  460,
      459,  458,  457,  456,  455,  454,  453,  452,  451,  450,
      328,  328,   52,   52,   52,   52,   52,   55,   55,   56,
      449,   56,   56,   56,   68,  448,   68,  329,  447,  329,

      329,  329,  328,  328,  328,  328,  328,  446,  445,  444,
      443,  442,  441,  440,  439,  438,  437,  436,  435,  434,
      433,  432,  431,  430,  429,  428,  427,  426,  425,  424,
      423,  422,  421,  420,  419,  418,  417,  416,  415,  414,
      413,  412,  411,  410,  330,  408,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  356,  355,  354,  353,  352,

      351,  350,  349,  348,  347,  346,  345,  344,  343,  340,
      339,  338,  337,  334,  333,  332,  331,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  254,  253,  252,  251,  250,  247,  246,  245,
      244,  241,  238,  233,  232,  231,  230,  223,  219,  215,

      214,  213,  212,  211,  210,  209,  206,  205,  202,  201,
      200,  199,  198,  197,  196,  195,  189,  188,  187,  186,
      183,  180,  179,  178,  175,  174,  166,  165,  164,  163,
      160,  159,  156,  155,  527,   50,  149,   67,   66,   59,
       58,   57,   50,  527,    3,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,

      527
    } ;

static const flex_int16_t yy_chk[702] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    6,    6,    7,    7,
        8,   18,   18,   18,   18,   18,   18,   19,   19,   19,
       19,   19,   19,   20,   20,   20,   20,   20,   20,   21,
       21,   21,   21,   21,   21,   24,   24,   27,  525,   35,
       28,   21,   27,   27,   28,   39,   29,   35,   28,   29,

       89,   28,   30,   89,   28,   39,   30,   28,    8,   29,
       30,   31,   32,   45,   28,   45,   30,   33,  523,   34,
       31,   91,   31,   34,   30,   75,   32,   34,   91,   32,
       31,   33,   31,   34,   33,   37,   38,   41,   38,   37,
       40,   41,   52,   37,   38,   75,   40,   41,   40,   37,
       38,   42,   40,   41,   38,   42,   38,   97,   43,   42,
       43,   97,   44,   49,   46,   42,   44,   72,   46,   44,
       44,   43,   46,   47,   49,   43,   44,   47,   72,   44,
       47,   47,   44,   51,   51,   56,   56,   47,   57,   57,
       52,   60,   60,   60,   60,   60,   60,   61,   61,   61,

       61,   61,   61,   62,   62,   62,   62,   62,   62,   61,
       80,   81,   82,   81,   82,   62,   85,  516,   80,   80,
       96,  107,  110,  130,  514,   85,  122,   96,   96,  107,
      110,  120,  124,  122,  125,  120,  122,  124,  131,  135,
      130,   57,  133,  125,  120,  147,  125,  193,  135,  141,
      125,  131,  194,  133,  168,  141,  193,  168,  232,  254,
      237,  147,  328,  328,  513,  511,  509,  254,  232,  508,
      507,  506,  194,  227,  227,  504,  503,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  237,  502,  500,
      496,  495,  494,  227,  227,  227,  227,  227,  493,  492,

      490,  488,  487,  486,  485,  484,  482,  481,  479,  477,
      476,  475,  474,  471,  470,  468,  467,  466,  465,  456,
      454,  452,  451,  450,  227,  227,  449,  447,  227,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  446,  444,  443,  440,  438,  437,  329,
      329,  329,  329,  329,  436,  433,  432,  428,  427,  426,
      425,  423,  420,  419,  418,  417,  415,  414,  413,  412,
      411,  410,  408,  407,  406,  405,  402,  400,  399,  398,
      329,  329,  528,  528,  528,  528,  528,  529,  529,  530,
      397,  530,  530,  530,  531,  396,  531,  532,  393,  532,

      532,  532,  533,  533,  533,  533,  533,  391,  390,  388,
      386,  384,  381,  379,  377,  376,  375,  374,  371,  369,
      367,  363,  359,  358,  357,  354,  353,  352,  351,  350,
      349,  347,  346,  344,  343,  342,  339,  338,  337,  336,
      335,  333,  332,  331,  330,  327,  326,  325,  324,  323,
      320,  319,  318,  316,  315,  314,  312,  311,  309,  308,
      307,  306,  305,  304,  301,  299,  297,  295,  293,  292,
      290,  289,  288,  286,  283,  282,  279,  277,  276,  275,
      273,  271,  270,  268,  267,  266,  264,  262,  261,  260,
      259,  258,  257,  256,  255,  253,  252,  251,  250,  249,

      247,  246,  245,  244,  243,  242,  241,  240,  239,  236,
      235,  234,  233,  231,  230,  229,  228,  225,  224,  223,
      222,  220,  219,  217,  216,  215,  214,  211,  210,  209,
      208,  207,  205,  204,  203,  202,  201,  200,  199,  198,
      196,  195,  192,  191,  190,  189,  188,  186,  185,  184,
      183,  182,  181,  180,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  155,  154,  153,  151,  150,
      149,  148,  146,  145,  144,  143,  142,  140,  139,  138,
      137,  134,  132,  129,  128,  127,  126,  123,  121,  119,

      117,  116,  115,  114,  113,  111,  109,  108,  106,  105,
      104,  103,  101,  100,   99,   98,   95,   94,   93,   92,
       90,   88,   87,   86,   84,   83,   79,   78,   77,   76,
       74,   73,   69,   63,   54,   50,   48,   26,   25,   17,
       15,   11,    5,    3,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,

      527
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[166] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 1, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/ugbc.lex"
#line 2 "src/ugbc.lex"

#include <string.h>
#include "ugbc.tab.h" /* The tokens */
#line 810 "src-generated/ugbc.yy.c"
#line 811 "src-generated/ugbc.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 9 "src/ugbc.lex"


#line 1031 "src-generated/ugbc.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 528 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 645 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 11 "src/ugbc.lex"
{ return(NewLine);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 12 "src/ugbc.lex"
{ return(SEMICOLON); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 13 "src/ugbc.lex"
{ return(COLON); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 14 "src/ugbc.lex"
{ return(OP); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 15 "src/ugbc.lex"
{ return(CP); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 16 "src/ugbc.lex"
{ return(COMMA); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 17 "src/ugbc.lex"
{ return(ASSIGN); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 18 "src/ugbc.lex"
{ return(EQUAL); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 19 "src/ugbc.lex"
{ return(PLUS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 20 "src/ugbc.lex"
{ return(MINUS); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 21 "src/ugbc.lex"
{ return(INCREMENT); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 22 "src/ugbc.lex"
{ return(DECREMENT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 23 "src/ugbc.lex"
{ return(HASH); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 24 "src/ugbc.lex"
{ return(LT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 25 "src/ugbc.lex"
{ return(LTE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 26 "src/ugbc.lex"
{ return(GT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 27 "src/ugbc.lex"
{ return(GTE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "src/ugbc.lex"
{ return(DISEQUAL); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 "src/ugbc.lex"
{ return(MULTIPLICATION); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 30 "src/ugbc.lex"
{ return(DOLLAR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 32 "src/ugbc.lex"
{ return (BYTE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 33 "src/ugbc.lex"
{ return (WORD); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 34 "src/ugbc.lex"
{ return (DWORD); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 36 "src/ugbc.lex"
{ return (AS); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 37 "src/ugbc.lex"
{ return (AT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 38 "src/ugbc.lex"
{ return (AND); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 39 "src/ugbc.lex"
{ return (BACKGROUND); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 40 "src/ugbc.lex"
{ return (BANK); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 41 "src/ugbc.lex"
{ return (BEG); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 42 "src/ugbc.lex"
{ return (BITMAP); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 43 "src/ugbc.lex"
{ return (BLACK); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 44 "src/ugbc.lex"
{ return (BLUE); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 45 "src/ugbc.lex"
{ return(BROWN); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 46 "src/ugbc.lex"
{ return (BYTE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 47 "src/ugbc.lex"
{ return (BORDER); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 48 "src/ugbc.lex"
{ return (CLEAR); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 49 "src/ugbc.lex"
{ return (CODE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 50 "src/ugbc.lex"
{ return (COLLISION); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 51 "src/ugbc.lex"
{ return (COLOR); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 52 "src/ugbc.lex"
{ return (COLORMAP); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 53 "src/ugbc.lex"
{ return (COMPRESS); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 54 "src/ugbc.lex"
{ return(CYAN); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 55 "src/ugbc.lex"
{ return (CYCLES); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 56 "src/ugbc.lex"
{ return(DARK); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 57 "src/ugbc.lex"
{ return (DATA); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 58 "src/ugbc.lex"
{ return (DEBUG); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 59 "src/ugbc.lex"
{ return (DISABLE); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 60 "src/ugbc.lex"
{ return (DONE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 61 "src/ugbc.lex"
{ return (DO); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 62 "src/ugbc.lex"
{ return (DOWN); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 63 "src/ugbc.lex"
{ return (DWORD); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 64 "src/ugbc.lex"
{ return(ECM); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 65 "src/ugbc.lex"
{ return(ELSE); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 66 "src/ugbc.lex"
{ return (END); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 67 "src/ugbc.lex"
{ return (ENDIF); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 68 "src/ugbc.lex"
{ return (ENABLE); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 69 "src/ugbc.lex"
{ return (EXIT); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 70 "src/ugbc.lex"
{ return (EXPAND); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 71 "src/ugbc.lex"
{ return (EVERY); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 72 "src/ugbc.lex"
{ return(FALSE); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 73 "src/ugbc.lex"
{ return(FOR); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 74 "src/ugbc.lex"
{ return (FROM); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 75 "src/ugbc.lex"
{ return (GAMELOOP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 76 "src/ugbc.lex"
{ return(GOLD); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 77 "src/ugbc.lex"
{ return (GOTO); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 78 "src/ugbc.lex"
{ return (GOSUB); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 79 "src/ugbc.lex"
{ return (GRAPHIC); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 80 "src/ugbc.lex"
{ return(GRAY); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 81 "src/ugbc.lex"
{ return(GREEN); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 82 "src/ugbc.lex"
{ return(GREY); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 83 "src/ugbc.lex"
{ return (HALT); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 84 "src/ugbc.lex"
{ return (HEIGHT); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 85 "src/ugbc.lex"
{ return (HIT); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 86 "src/ugbc.lex"
{ return (HORIZONTAL); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 87 "src/ugbc.lex"
{ return (IF); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 88 "src/ugbc.lex"
{ return (INSTR); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 89 "src/ugbc.lex"
{ return(LAVENDER); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 90 "src/ugbc.lex"
{ return (LEFT); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 91 "src/ugbc.lex"
{ return (LEFT); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 92 "src/ugbc.lex"
{ return(LIGHT); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 93 "src/ugbc.lex"
{ return (LOOP); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 94 "src/ugbc.lex"
{ return (LOWER); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 95 "src/ugbc.lex"
{ return (LOWER); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 96 "src/ugbc.lex"
{ return(MAGENTA); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 97 "src/ugbc.lex"
{ return (NEXT); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 98 "src/ugbc.lex"
{ return(MCM); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 99 "src/ugbc.lex"
{ return(MID); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 100 "src/ugbc.lex"
{ return(MID); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 101 "src/ugbc.lex"
{ return(MONOCOLOR); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 102 "src/ugbc.lex"
{ return (MILLISECOND); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 103 "src/ugbc.lex"
{ return (MILLISECOND); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 104 "src/ugbc.lex"
{ return (MILLISECONDS); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 105 "src/ugbc.lex"
{ return(MULTICOLOR); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 106 "src/ugbc.lex"
{ return(NOT); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 107 "src/ugbc.lex"
{ return(OLIVE); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 108 "src/ugbc.lex"
{ return (OFF); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 109 "src/ugbc.lex"
{ return (ON); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 110 "src/ugbc.lex"
{ return (OR); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 111 "src/ugbc.lex"
{ return(ORANGE); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 112 "src/ugbc.lex"
{ return(PEACH); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 113 "src/ugbc.lex"
{ return (PEEK); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 114 "src/ugbc.lex"
{ return (PEN); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 115 "src/ugbc.lex"
{ return(PINK); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 116 "src/ugbc.lex"
{ return (POINT); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 117 "src/ugbc.lex"
{ return (POP); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 118 "src/ugbc.lex"
{ return (POSITION); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 119 "src/ugbc.lex"
{ return(PURPLE); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 120 "src/ugbc.lex"
{ return (RANDOM); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 121 "src/ugbc.lex"
{ return (RANDOMIZE); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 122 "src/ugbc.lex"
{ return (RASTER); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 123 "src/ugbc.lex"
{ return(RED); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 124 "src/ugbc.lex"
{ return (REPEAT); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 125 "src/ugbc.lex"
{ return (RETURN); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 126 "src/ugbc.lex"
{ return (RIGHT); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 127 "src/ugbc.lex"
{ return (RIGHT); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 128 "src/ugbc.lex"
{ return (ROWS); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 129 "src/ugbc.lex"
{ return (S); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 130 "src/ugbc.lex"
{ return (SCREEN); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 131 "src/ugbc.lex"
{ return (SCROLL); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 132 "src/ugbc.lex"
{ return (SELECT); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 133 "src/ugbc.lex"
{ return (SPACE); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 134 "src/ugbc.lex"
{ return (SPRITE); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 135 "src/ugbc.lex"
{ return (STEP); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 136 "src/ugbc.lex"
{ return (STR); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 137 "src/ugbc.lex"
{ return (STR); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 138 "src/ugbc.lex"
{ return (STRING); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 139 "src/ugbc.lex"
{ return (STRING); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 140 "src/ugbc.lex"
{ return(TAN); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 141 "src/ugbc.lex"
{ return (TEMPORARY); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 142 "src/ugbc.lex"
{ return (TEXT); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 143 "src/ugbc.lex"
{ return (TEXTMAP); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 144 "src/ugbc.lex"
{ return (THEN); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 145 "src/ugbc.lex"
{ return (TICKS); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 146 "src/ugbc.lex"
{ return (TILES); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 147 "src/ugbc.lex"
{ return (TO); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 148 "src/ugbc.lex"
{ return(TURQUOISE); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 149 "src/ugbc.lex"
{ return(TRUE); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 150 "src/ugbc.lex"
{ return (UNTIL); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 151 "src/ugbc.lex"
{ return (UP); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 152 "src/ugbc.lex"
{ return (UPPER); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 153 "src/ugbc.lex"
{ return (UPPER); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 154 "src/ugbc.lex"
{ return (VAL); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 155 "src/ugbc.lex"
{ return (VAR); }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 156 "src/ugbc.lex"
{ return (VARIABLES); }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 157 "src/ugbc.lex"
{ return (VERTICAL); }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 158 "src/ugbc.lex"
{ return(VIOLET); }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 159 "src/ugbc.lex"
{ return (WAIT); }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 160 "src/ugbc.lex"
{ return (WEND); }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 161 "src/ugbc.lex"
{ return (WITH); }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 162 "src/ugbc.lex"
{ return (WIDTH); }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 163 "src/ugbc.lex"
{ return (WHILE); }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 164 "src/ugbc.lex"
{ return(WHITE); }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 165 "src/ugbc.lex"
{ return (WORD); }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 166 "src/ugbc.lex"
{ return (XPEN); }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 167 "src/ugbc.lex"
{ return(YELLOW); }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 168 "src/ugbc.lex"
{ return (YPEN); }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 170 "src/ugbc.lex"
{ yylval.string = strdup(yytext); return(Identifier);  }
	YY_BREAK
case 158:
/* rule 158 can match eol */
YY_RULE_SETUP
#line 171 "src/ugbc.lex"
{ yylval.string = strdup(yytext); memcpy(yylval.string,yylval.string+1,strlen(yylval.string)); yylval.string[strlen(yylval.string)-1]=0; return(String);  }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 172 "src/ugbc.lex"
{ yylval.integer = strtol(yytext+1,0,16); return(Integer); }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 173 "src/ugbc.lex"
{ yylval.integer = atoi(yytext); return(Integer);  }
	YY_BREAK
case 161:
/* rule 161 can match eol */
YY_RULE_SETUP
#line 174 "src/ugbc.lex"
{ return(Remark);  }
	YY_BREAK
case 162:
/* rule 162 can match eol */
YY_RULE_SETUP
#line 175 "src/ugbc.lex"
{ return(Remark);  }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 177 "src/ugbc.lex"

	YY_BREAK
case 164:
YY_RULE_SETUP
#line 178 "src/ugbc.lex"
{ return(yytext[0]); }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 180 "src/ugbc.lex"
ECHO;
	YY_BREAK
#line 1927 "src-generated/ugbc.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 528 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 528 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 527);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 180 "src/ugbc.lex"


