#line 2 "src-generated/ugbc.yy.c"

#line 4 "src-generated/ugbc.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 142
#define YY_END_OF_BUFFER 143
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[484] =
    {   0,
        0,    0,  143,  141,  140,    1,    1,  141,   13,  141,
      141,    4,    5,    9,    6,   10,  137,  137,  137,  137,
        3,    2,   14,    7,   16,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  106,  134,  134,  134,  134,  134,  134,  140,    1,
        0,  135,    0,  136,    0,    0,   11,   12,  137,  137,
      137,    0,   15,   18,    8,   17,  134,  134,   22,   23,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,   47,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,   71,  134,

      134,  134,  134,  134,  134,  134,  134,   80,  134,  134,
      134,  134,  134,   87,   88,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  120,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  139,    0,    0,    0,   24,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
       50,  134,  134,   52,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,   69,  134,  134,  134,
      134,  134,  134,   78,  134,  134,  134,  134,   84,   86,

      134,  134,  134,  134,   92,  134,  134,   95,  134,  134,
      134,  134,  101,  134,  134,  134,  134,  134,  134,  134,
      134,  111,  134,  134,  134,  134,  134,  134,  134,  121,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
        0,    0,   19,  134,   26,  134,  134,  134,   30,  134,
      134,   32,  134,   35,  134,  134,  134,   40,  134,   42,
       43,  134,  134,   46,   48,  134,   51,  134,  134,   55,
      134,  134,   58,  134,   60,  134,   61,  134,   64,  134,
       66,   67,  134,  134,  134,   73,  134,   75,  134,  134,
      134,  134,   77,  134,  134,  134,   91,   93,  134,  134,

      134,  134,  134,    0,  134,  134,  134,  134,  134,  105,
      134,  134,  134,  134,  134,  113,  115,  134,  134,  119,
      134,  134,  134,  134,  125,  134,  134,  134,  126,  130,
      131,  134,  133,   20,   21,  134,   27,  134,   29,  134,
       31,   34,  134,   37,  134,  134,   44,  134,   49,  134,
       53,  134,   57,  134,   62,  134,   65,  134,  134,  134,
       74,  134,  134,  134,  134,   85,  134,   90,   94,  134,
      134,  134,  134,  138,  134,  134,  104,  134,  134,  134,
      134,  134,  134,  116,  117,  134,  134,  134,  134,  128,
      129,  127,  134,  134,   28,   33,  134,  134,  134,   41,

      134,   54,   56,  134,  134,   68,  134,  134,  134,  134,
      134,  134,   89,  134,   97,   98,  100,  102,  103,  107,
      108,  109,  110,  134,  134,  134,  134,  134,  124,  132,
      134,  134,  134,  134,   45,  134,   63,  134,  134,   76,
      134,  134,  134,  134,  134,  134,  114,  134,  134,  134,
      134,  134,   38,   39,   59,  134,   72,  134,  134,  134,
       96,  134,  134,  134,  134,  123,  134,   36,  134,  134,
       79,  134,   99,  112,  118,  122,   25,   70,  134,   83,
       81,   82,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    1,    8,    9,
       10,    1,   11,   12,   13,    1,    1,   14,   15,   16,
       17,   14,   14,   18,   14,   19,   14,   20,   21,   22,
       23,   24,    1,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   51,   51,   53,   51,   34,   34,   34,   34,

       34,   34,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   55,   54,   54,   54,   54,   54,
       54,   54,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        4,    4,    3,    5,    5
    } ;

static const flex_int16_t yy_base[490] =
    {   0,
        0,    0,  598,  599,  595,   53,   55,   55,  599,    0,
      541,  599,  599,  584,  599,  581,   47,   53,   59,   65,
      599,  599,   62,  570,  569,   49,   69,   60,   81,   77,
       70,   91,   98,  561,    0,  107,  114,   61,  112,  116,
      127,   95,  138,  550,  139,  149,  549,  122,  586,   85,
       92,  599,  584,    0,  172,  174,  599,  599,  175,  181,
      187,  553,  599,  599,  599,  599,    0,  557,    0,    0,
      131,  553,  539,   76,  540,  542,  536,  550,  180,   92,
      142,  552,  534,   91,  537,  538,  531,  184,  178,  537,
      533,  534,  178,  190,  534,  536,  524,  525,    0,  520,

      535,  533,  524,  531,  524,  524,  521,    0,  522,  509,
      512,  525,  521,    0,  528,  195,  514,  192,  509,  185,
      199,  519,  502,  506,  511,  504,  507,  189,  515,  107,
      498,  500,    0,  499,  498,  500,  505,  504,  202,  494,
      506,  498,  504,  599,  499,  498,  486,    0,  494,  493,
      494,  489,  498,  495,  495,  475,  492,  495,  490,  195,
      478,  479,  480,  480,  489,  468,  487,  482,  472,  467,
        0,  479,  481,  473,  461,  479,  460,  465,  472,  472,
      454,  459,  198,  136,  453,  465,    0,  462,  465,  449,
      460,  451,  461,    0,  453,  449,  443,  442,    0,    0,

      439,  446,  456,  447,    0,  446,  442,    0,  446,  438,
      449,  432,    0,  247,  446,  429,  441,  429,  211,  442,
      437,    0,  429,  424,  429,  431,  436,  435,  422,  429,
      417,  424,  415,  143,  414,  425,  428,  417,  418,  415,
      408,  407,  599,  419,    0,  411,  423,  412,    0,  417,
      407,    0,  402,    0,  410,  400,  399,    0,  411,    0,
        0,  408,  412,    0,    0,  409,    0,  400,  405,    0,
      396,  404,    0,  396,    0,  405,    0,  398,    0,  391,
        0,    0,  396,  377,  388,    0,  381,    0,  386,  390,
      395,  388,    0,  391,  388,  386,    0,    0,  373,  372,

      379,  375,  384,  238,  302,  357,  386,  368,  365,    0,
      379,  371,  379,  361,  365,  366,    0,  359,  358,    0,
      355,  374,  365,  368,    0,  367,  366,  362,    0,    0,
        0,  354,    0,  599,  599,  350,    0,  351,    0,  348,
        0,    0,  346,  351,  358,  343,    0,  349,    0,  355,
        0,  355,    0,  343,    0,  348,    0,  336,  332,  340,
        0,  319,  309,  312,  323,    0,  320,    0,    0,  315,
      318,  309,  303,  599,  300,  305,    0,  304,  305,  296,
      310,  296,  312,    0,    0,  297,  309,  307,  289,    0,
        0,    0,  285,  292,    0,    0,  297,  304,  285,    0,

      298,    0,    0,  282,  293,    0,  281,  289,  292,  287,
      265,  261,    0,  258,    0,  263,    0,    0,    0,    0,
        0,    0,    0,  270,  254,  260,  256,  266,    0,    0,
      245,  250,  248,  244,    0,  246,    0,  241,  242,    0,
      256,  243,  245,  242,  229,  236,    0,  234,  247,  239,
      236,  235,    0,    0,    0,  247,    0,  227,  223,  225,
        0,  234,  213,  232,  208,    0,  217,    0,  208,  172,
        0,  131,    0,    0,    0,    0,    0,    0,   98,    0,
       60,    0,  599,  354,  357,  361,  364,  369,  374
    } ;

static const flex_int16_t yy_def[490] =
    {   0,
      483,    1,  483,  483,  483,  483,  483,  484,  483,  485,
      486,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  483,  483,
      484,  483,  484,  485,  486,  486,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  483,  483,  483,  483,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  488,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      483,  483,  483,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  489,  488,  305,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  483,  483,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  483,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,    0,  483,  483,  483,  483,  483,  483
    } ;

static const flex_int16_t yy_nxt[655] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   17,   19,   17,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   35,   36,   37,   38,   39,   40,
       35,   41,   42,   43,   44,   45,   46,   47,   48,   35,
        4,    4,    4,   35,   35,   50,   50,   50,   50,   52,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       60,   59,   59,   59,   61,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   63,   64,   68,   50,   50,  110,
       62,   69,   70,   71,   90,   78,   52,   72,   79,  111,

      153,   73,  482,   86,   74,   81,   53,   75,   80,   82,
       76,   91,   87,   83,   88,   92,  162,   77,  163,   84,
      154,  124,   95,  125,   89,  481,   96,   85,  168,   93,
       97,  100,   94,  226,  126,  101,   98,  169,  104,  102,
      105,  112,  227,   53,  116,  103,  106,  113,  117,  114,
      142,  120,  107,  115,  118,  121,  108,  149,  109,  122,
      119,  143,  127,  134,  280,  123,  128,  135,  150,  129,
      130,  136,  480,  137,  144,  144,  144,  144,  326,  131,
      138,  139,  132,  164,  281,  165,  327,  140,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   59,  145,  159,  173,  479,
      175,  174,  146,  180,  183,  160,  161,  176,  184,  203,
      181,  182,  211,  204,  207,  223,  213,  212,   56,  235,
      255,  208,  205,  256,  209,  214,  224,  278,  215,  311,
      374,  374,  216,  478,  477,  236,  279,  304,  304,  312,
      476,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      475,  474,  473,  472,  471,  470,  304,  304,  304,  304,
      304,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  304,  304,  443,

      442,  306,  304,  304,  374,  374,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  441,  440,  439,  438,  437,
      436,  304,  304,  304,  304,  304,  435,  434,  433,  432,
      431,  430,  429,  428,  427,  426,  425,  424,  423,  422,
      421,  420,  419,  418,  417,  416,  415,  414,  413,  412,
      411,  410,  304,  304,   51,   51,   51,   51,   51,   54,
       54,   55,  409,   55,   55,   55,   67,  408,   67,  305,
      407,  305,  305,  305,  304,  304,  304,  304,  304,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,

      385,  384,  383,  382,  381,  380,  379,  378,  377,  376,
      375,  306,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  310,  309,  308,  307,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  277,  276,  275,

      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  234,  233,  232,  231,
      230,  229,  228,  225,  222,  221,  220,  219,  218,  217,
      210,  206,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      179,  178,  177,  172,  171,  170,  167,  166,  158,  157,
      156,  155,  152,  151,  148,  147,  483,   49,  141,  133,
       99,   66,   65,   58,   57,   56,   49,  483,    3,  483,

      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483
    } ;

static const flex_int16_t yy_chk[655] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    6,    6,    7,    7,    8,
       17,   17,   17,   17,   17,   17,   18,   18,   18,   18,
       18,   18,   19,   19,   19,   19,   19,   19,   20,   20,
       20,   20,   20,   20,   23,   23,   26,   50,   50,   38,
       20,   26,   26,   27,   31,   28,   51,   27,   28,   38,

       74,   27,  481,   30,   27,   29,    8,   27,   28,   29,
       27,   31,   30,   29,   30,   32,   80,   27,   80,   29,
       74,   42,   33,   42,   30,  479,   33,   29,   84,   32,
       33,   36,   32,  130,   42,   36,   33,   84,   37,   36,
       37,   39,  130,   51,   40,   36,   37,   39,   40,   39,
       48,   41,   37,   39,   40,   41,   37,   71,   37,   41,
       40,   48,   43,   45,  184,   41,   43,   45,   71,   43,
       43,   45,  472,   46,   55,   55,   56,   56,  234,   43,
       46,   46,   43,   81,  184,   81,  234,   46,   59,   59,
       59,   59,   59,   59,   60,   60,   60,   60,   60,   60,

       61,   61,   61,   61,   61,   61,   60,   79,   88,  470,
       89,   88,   61,   93,   94,   79,   79,   89,   94,  116,
       93,   93,  120,  116,  118,  128,  121,  120,   56,  139,
      160,  118,  116,  160,  118,  121,  128,  183,  121,  219,
      304,  304,  121,  469,  467,  139,  183,  214,  214,  219,
      465,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      464,  463,  462,  460,  459,  458,  214,  214,  214,  214,
      214,  456,  452,  451,  450,  449,  448,  446,  445,  444,
      443,  442,  441,  439,  438,  436,  434,  433,  432,  431,
      428,  427,  426,  425,  424,  416,  414,  214,  214,  412,

      411,  214,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  410,  409,  408,  407,  405,
      404,  305,  305,  305,  305,  305,  401,  399,  398,  397,
      394,  393,  389,  388,  387,  386,  383,  382,  381,  380,
      379,  378,  376,  375,  373,  372,  371,  370,  367,  365,
      364,  363,  305,  305,  484,  484,  484,  484,  484,  485,
      485,  486,  362,  486,  486,  486,  487,  360,  487,  488,
      359,  488,  488,  488,  489,  489,  489,  489,  489,  358,
      356,  354,  352,  350,  348,  346,  345,  344,  343,  340,
      338,  336,  332,  328,  327,  326,  324,  323,  322,  321,

      319,  318,  316,  315,  314,  313,  312,  311,  309,  308,
      307,  306,  303,  302,  301,  300,  299,  296,  295,  294,
      292,  291,  290,  289,  287,  285,  284,  283,  280,  278,
      276,  274,  272,  271,  269,  268,  266,  263,  262,  259,
      257,  256,  255,  253,  251,  250,  248,  247,  246,  244,
      242,  241,  240,  239,  238,  237,  236,  235,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  221,
      220,  218,  217,  216,  215,  212,  211,  210,  209,  207,
      206,  204,  203,  202,  201,  198,  197,  196,  195,  193,
      192,  191,  190,  189,  188,  186,  185,  182,  181,  180,

      179,  178,  177,  176,  175,  174,  173,  172,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  147,
      146,  145,  143,  142,  141,  140,  138,  137,  136,  135,
      134,  132,  131,  129,  127,  126,  125,  124,  123,  122,
      119,  117,  115,  113,  112,  111,  110,  109,  107,  106,
      105,  104,  103,  102,  101,  100,   98,   97,   96,   95,
       92,   91,   90,   87,   86,   85,   83,   82,   78,   77,
       76,   75,   73,   72,   68,   62,   53,   49,   47,   44,
       34,   25,   24,   16,   14,   11,    5,    3,  483,  483,

      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[143] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/ugbc.lex"
#line 2 "src/ugbc.lex"

#include <string.h>
#include "ugbc.tab.h" /* The tokens */
#line 780 "src-generated/ugbc.yy.c"
#line 781 "src-generated/ugbc.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 9 "src/ugbc.lex"


#line 1001 "src-generated/ugbc.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 484 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 599 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 11 "src/ugbc.lex"
{ return(NewLine);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 12 "src/ugbc.lex"
{ return(SEMICOLON); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 13 "src/ugbc.lex"
{ return(COLON); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 14 "src/ugbc.lex"
{ return(OP); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 15 "src/ugbc.lex"
{ return(CP); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 16 "src/ugbc.lex"
{ return(COMMA); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 17 "src/ugbc.lex"
{ return(ASSIGN); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 18 "src/ugbc.lex"
{ return(EQUAL); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 19 "src/ugbc.lex"
{ return(PLUS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 20 "src/ugbc.lex"
{ return(MINUS); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 21 "src/ugbc.lex"
{ return(INCREMENT); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 22 "src/ugbc.lex"
{ return(DECREMENT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 23 "src/ugbc.lex"
{ return(HASH); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 24 "src/ugbc.lex"
{ return(LT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 25 "src/ugbc.lex"
{ return(LTE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 26 "src/ugbc.lex"
{ return(GT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 27 "src/ugbc.lex"
{ return(GTE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "src/ugbc.lex"
{ return(DISEQUAL); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 30 "src/ugbc.lex"
{ return (BYTE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 31 "src/ugbc.lex"
{ return (WORD); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 32 "src/ugbc.lex"
{ return (DWORD); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 34 "src/ugbc.lex"
{ return (AS); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 35 "src/ugbc.lex"
{ return (AT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 36 "src/ugbc.lex"
{ return (AND); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 37 "src/ugbc.lex"
{ return (BACKGROUND); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 38 "src/ugbc.lex"
{ return (BANK); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 39 "src/ugbc.lex"
{ return (BEG); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 40 "src/ugbc.lex"
{ return (BITMAP); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 41 "src/ugbc.lex"
{ return (BLACK); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 42 "src/ugbc.lex"
{ return (BLUE); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 43 "src/ugbc.lex"
{ return(BROWN); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 44 "src/ugbc.lex"
{ return (BYTE); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 45 "src/ugbc.lex"
{ return (BORDER); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 46 "src/ugbc.lex"
{ return (CLEAR); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 47 "src/ugbc.lex"
{ return (CODE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 48 "src/ugbc.lex"
{ return (COLLISION); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 49 "src/ugbc.lex"
{ return (COLOR); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 50 "src/ugbc.lex"
{ return (COLORMAP); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 51 "src/ugbc.lex"
{ return (COMPRESS); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 52 "src/ugbc.lex"
{ return(CYAN); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 53 "src/ugbc.lex"
{ return (CYCLES); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 54 "src/ugbc.lex"
{ return(DARK); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 55 "src/ugbc.lex"
{ return (DATA); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 56 "src/ugbc.lex"
{ return (DEBUG); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 57 "src/ugbc.lex"
{ return (DISABLE); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 58 "src/ugbc.lex"
{ return (DONE); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 59 "src/ugbc.lex"
{ return (DO); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 60 "src/ugbc.lex"
{ return (DOWN); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 61 "src/ugbc.lex"
{ return (DWORD); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 62 "src/ugbc.lex"
{ return(ECM); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 63 "src/ugbc.lex"
{ return(ELSE); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 64 "src/ugbc.lex"
{ return (END); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 65 "src/ugbc.lex"
{ return (ENDIF); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 66 "src/ugbc.lex"
{ return (ENABLE); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 67 "src/ugbc.lex"
{ return (EXPAND); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 68 "src/ugbc.lex"
{ return (EXPAND); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 69 "src/ugbc.lex"
{ return(FALSE); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 70 "src/ugbc.lex"
{ return (FROM); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 71 "src/ugbc.lex"
{ return (GAMELOOP); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 72 "src/ugbc.lex"
{ return(GOLD); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 73 "src/ugbc.lex"
{ return (GOTO); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 74 "src/ugbc.lex"
{ return (GOSUB); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 75 "src/ugbc.lex"
{ return (GRAPHIC); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 76 "src/ugbc.lex"
{ return(GRAY); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 77 "src/ugbc.lex"
{ return(GREEN); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 78 "src/ugbc.lex"
{ return(GREY); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 79 "src/ugbc.lex"
{ return (HALT); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 80 "src/ugbc.lex"
{ return (HEIGHT); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 81 "src/ugbc.lex"
{ return (HIT); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 82 "src/ugbc.lex"
{ return (HORIZONTAL); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 83 "src/ugbc.lex"
{ return (IF); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 84 "src/ugbc.lex"
{ return(LAVENDER); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 85 "src/ugbc.lex"
{ return (LEFT); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 86 "src/ugbc.lex"
{ return(LIGHT); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 87 "src/ugbc.lex"
{ return (LOOP); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 88 "src/ugbc.lex"
{ return(MAGENTA); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 89 "src/ugbc.lex"
{ return (NEXT); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 90 "src/ugbc.lex"
{ return(MCM); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 91 "src/ugbc.lex"
{ return(MONOCOLOR); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 92 "src/ugbc.lex"
{ return (MILLISECOND); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 93 "src/ugbc.lex"
{ return (MILLISECOND); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 94 "src/ugbc.lex"
{ return (MILLISECONDS); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 95 "src/ugbc.lex"
{ return(MULTICOLOR); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 96 "src/ugbc.lex"
{ return(NOT); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 97 "src/ugbc.lex"
{ return(OLIVE); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 98 "src/ugbc.lex"
{ return (OFF); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 99 "src/ugbc.lex"
{ return (ON); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 100 "src/ugbc.lex"
{ return (OR); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 101 "src/ugbc.lex"
{ return(ORANGE); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 102 "src/ugbc.lex"
{ return(PEACH); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 103 "src/ugbc.lex"
{ return (PEEK); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 104 "src/ugbc.lex"
{ return (PEN); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 105 "src/ugbc.lex"
{ return(PINK); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 106 "src/ugbc.lex"
{ return (POINT); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 107 "src/ugbc.lex"
{ return (POP); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 108 "src/ugbc.lex"
{ return (POSITION); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 109 "src/ugbc.lex"
{ return(PURPLE); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 110 "src/ugbc.lex"
{ return (RANDOM); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 111 "src/ugbc.lex"
{ return (RANDOMIZE); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 112 "src/ugbc.lex"
{ return (RASTER); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 113 "src/ugbc.lex"
{ return(RED); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 114 "src/ugbc.lex"
{ return (REPEAT); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 115 "src/ugbc.lex"
{ return (RETURN); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 116 "src/ugbc.lex"
{ return (RIGHT); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 117 "src/ugbc.lex"
{ return (ROWS); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 118 "src/ugbc.lex"
{ return (S); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 119 "src/ugbc.lex"
{ return (SCREEN); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 120 "src/ugbc.lex"
{ return (SCROLL); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 121 "src/ugbc.lex"
{ return (SELECT); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 122 "src/ugbc.lex"
{ return (SPRITE); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 123 "src/ugbc.lex"
{ return(TAN); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 124 "src/ugbc.lex"
{ return (TEMPORARY); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 125 "src/ugbc.lex"
{ return (TEXT); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 126 "src/ugbc.lex"
{ return (TEXTMAP); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 127 "src/ugbc.lex"
{ return (THEN); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 128 "src/ugbc.lex"
{ return (TICKS); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 129 "src/ugbc.lex"
{ return (TILES); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 130 "src/ugbc.lex"
{ return(TURQUOISE); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 131 "src/ugbc.lex"
{ return(TRUE); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 132 "src/ugbc.lex"
{ return (UP); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 133 "src/ugbc.lex"
{ return (VAR); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 134 "src/ugbc.lex"
{ return (VARIABLES); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 135 "src/ugbc.lex"
{ return (VERTICAL); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 136 "src/ugbc.lex"
{ return(VIOLET); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 137 "src/ugbc.lex"
{ return (WAIT); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 138 "src/ugbc.lex"
{ return (WITH); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 139 "src/ugbc.lex"
{ return (WIDTH); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 140 "src/ugbc.lex"
{ return (WHILE); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 141 "src/ugbc.lex"
{ return(WHITE); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 142 "src/ugbc.lex"
{ return (WORD); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 143 "src/ugbc.lex"
{ return (XPEN); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 144 "src/ugbc.lex"
{ return(YELLOW); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 145 "src/ugbc.lex"
{ return (YPEN); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 147 "src/ugbc.lex"
{ yylval.string = strdup(yytext); return(Identifier);  }
	YY_BREAK
case 135:
/* rule 135 can match eol */
YY_RULE_SETUP
#line 148 "src/ugbc.lex"
{ yylval.string = strdup(yytext); memcpy(yylval.string,yylval.string+1,strlen(yylval.string)); yylval.string[strlen(yylval.string)-1]=0; return(String);  }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 149 "src/ugbc.lex"
{ yylval.integer = strtol(yytext+1,0,16); return(Integer); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 150 "src/ugbc.lex"
{ yylval.integer = atoi(yytext); return(Integer);  }
	YY_BREAK
case 138:
/* rule 138 can match eol */
YY_RULE_SETUP
#line 151 "src/ugbc.lex"
{ return(Remark);  }
	YY_BREAK
case 139:
/* rule 139 can match eol */
YY_RULE_SETUP
#line 152 "src/ugbc.lex"
{ return(Remark);  }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 154 "src/ugbc.lex"

	YY_BREAK
case 141:
YY_RULE_SETUP
#line 155 "src/ugbc.lex"
{ return(yytext[0]); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 157 "src/ugbc.lex"
ECHO;
	YY_BREAK
#line 1782 "src-generated/ugbc.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 484 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 484 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 483);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 157 "src/ugbc.lex"


