TEXTADDRESS:        .BYTE   0, 4
BITMAPADDRESS:      .WORD   $2000
COLORMAPADDRESS:       .BYTE   0, $D8
TABCOUNT:   .BYTE    4
LOCALPEN:   .BYTE    0
LOCALPAPER: .BYTE    7
XCURS:      .BYTE    0
YCURS:      .BYTE    0
LOCALWW:    .BYTE    3
EMPTYTILE:  .BYTE   32
