; Z80FLOAT IS A FLOATING POINT LIBRARY TARGETING THE Z80 PROCESSOR. WHILE THIS
; PROJECT IS TESTED ON A TI-84+, THE CODE SHOULD BE GENERIC ENOUGH TO RUN ON ANY
; Z80 CPU WITH VERY LITTLE MODIFICATION (MOSTLY DEFINING SCRAP RAM LOCATIONS).
;
; ADAPTED BY MARCO SPEDALETTI

FPFASTGEOMEAN:

	XOR C
	JP P, FPFASTGEOMEANL1
	LD A, $7F
	LD H, A
	RET

FPFASTGEOMEANL1:

	XOR C
	AND $7F
	RET Z	 ;MAY AS WELL EXIT IF THE INPUT IS 0
	CP $7F
	JR Z, FPFASTGEOMEAN_SUB
	LD B, A

	LD A, C
	AND $7F
	RET Z
	CP $7F
	JR Z, FPFASTGEOMEAN_SUB

	ADD A, B
	RRA
	PUSH AF

	LD A, 63
	LD C, A
	ADC A, 0
	CALL FPFASTGEOMEAN_SUB
	POP BC
	ADD A, B
	SUB 63
	RET

FPFASTGEOMEAN_SUB:
	CALL FPFASTMUL
	JP FPFASTSQRT
