
CONSOLECALCULATE:
    LDA CURRENTMODE
    CMP #0
    BEQ CONSOLECALCULATE0
    CMP #1
    BEQ CONSOLECALCULATE1
    ; CMP #2
    ; BEQ CONSOLECALCULATE2
    ; CMP #3
    ; BEQ CONSOLECALCULATE3
    RTS

CONSOLECALCULATE0:
CONSOLECALCULATE1:
    LDA TEXTADDRESS
    STA MATHPTR0
    LDA TEXTADDRESS+1
    STA MATHPTR1
    LDX CONSOLEY1
    CPX #0
    BEQ CONSOLECALCULATEL1N
CONSOLECALCULATEL1:
    CLC
    LDA MATHPTR0
    ADC CURRENTTILESWIDTH
    STA MATHPTR0
    LDA MATHPTR1
    ADC #0
    STA MATHPTR1
    DEX
    BNE CONSOLECALCULATEL1
CONSOLECALCULATEL1N:
    CLC
    LDA MATHPTR0
    ADC CONSOLEX1
    STA MATHPTR0
    LDA MATHPTR1
    ADC #0
    STA MATHPTR1
    LDA MATHPTR0
    STA CONSOLESA
    LDA MATHPTR1
    STA CONSOLESA+1
    LDA CONSOLEW
    STA CONSOLEWB
    LDA CONSOLEH
    STA CONSOLEHB

    LDA COLORMAPADDRESS
    STA MATHPTR0
    LDA COLORMAPADDRESS+1
    STA MATHPTR1
    LDX CONSOLEY1
    CPX #0
    BNE CONSOLECALCULATECL1N
CONSOLECALCULATECL1:
    CLC
    LDA MATHPTR0
    ADC CURRENTTILESWIDTH
    STA MATHPTR0
    LDA MATHPTR1
    ADC #0
    STA MATHPTR1
    DEX
    BNE CONSOLECALCULATECL1
CONSOLECALCULATECL1N:
    CLC
    LDA MATHPTR0
    ADC CONSOLEX1
    STA MATHPTR0
    LDA MATHPTR1
    ADC #0
    STA MATHPTR1
    LDA MATHPTR0
    STA CONSOLECA
    LDA MATHPTR1
    STA CONSOLECA+1

    RTS

; CONSOLECALCULATE2:
; CONSOLECALCULATE3:
;     RTS
