
VSCROLLT:
    LDA $30
    CMP #$80
    BCC VSCROLLTDOWN

VSCROLLTUP:
    LDA TEXTADDRESS
    STA $25
    LDA TEXTADDRESS+1
    STA $26
    CLC
    LDA TEXTADDRESS
    ADC #40
    STA $27
    LDA TEXTADDRESS+1
    STA $28

    LDX #3
    LDY #0
VSCROLLTUPYSCR:
    LDA ($27),Y
    STA ($25),Y
    INY
    BNE VSCROLLTUPYSCR
    INC $26
    INC $28
    CPX #1
    BNE VSCROLLTUPYSCRNXT
VSCROLLTUPYSCR2:
    LDA ($27),Y
    STA ($25),Y
    INY
    CPY #232
    BNE VSCROLLTUPYSCR2
VSCROLLTUPYSCRNXT:
    DEX
    BNE VSCROLLTUPYSCR
    LDY #192
VSCROLLTUPREFILL:
    LDA #32
    STA ($25),Y
    INY
    CPY #232
    BNE VSCROLLTUPREFILL
    RTS

VSCROLLTDOWN:
    LDA TEXTADDRESS
    STA $25
    LDA TEXTADDRESS+1
    STA $26
    CLC
    LDA TEXTADDRESS
    ADC #40
    STA $27
    LDA TEXTADDRESS+1
    STA $28
    
    INC $26
    INC $28
    INC $26
    INC $28
    INC $26
    INC $28
    LDY #232
VSCROLLTDOWNYS3:
    LDA ($25),Y
    STA ($27),Y
    DEY
    CPY #255
    BNE VSCROLLTDOWNYS3

    DEC $26
    DEC $28
    LDX #3
    LDY #255
VSCROLLTDOWNYS4:
    LDA ($25),Y
    STA ($27),Y
    DEY
    CPY #255
    BNE VSCROLLTDOWNYS4

    DEC $26
    DEC $28
    LDY #255
    DEX
    BNE VSCROLLTDOWNYS4
    RTS
