
VSCROLLT:
    LDA $30
    CMP #$80
    BCC VSCROLLDOWN

VSCROLLUP:
    LDA TEXTADDRESS
    STA $25
    LDA TEXTADDRESS+1
    STA $26
    CLC
    LDA TEXTADDRESS
    ADC #40
    STA $27
    LDA TEXTADDRESS+1
    STA $28

    LDX #3
    LDY #0
VSCROLLUPYSCR:
    LDA ($27),Y
    STA ($25),Y
    INY
    BNE VSCROLLUPYSCR
    INC $26
    INC $28
    CPX #1
    BNE VSCROLLUPYSCRNXT
VSCROLLUPYSCR2:
    LDA ($27),Y
    STA ($25),Y
    INY
    CPY #232
    BNE VSCROLLUPYSCR2
VSCROLLUPYSCRNXT:
    DEX
    BNE VSCROLLUPYSCR
    LDY #192
VSCROLLUPREFILL:
    LDA #32
    STA ($25),Y
    INY
    CPY #232
    BNE VSCROLLUPREFILL
    RTS

VSCROLLDOWN:
    LDA TEXTADDRESS
    STA $25
    LDA TEXTADDRESS+1
    STA $26
    CLC
    LDA TEXTADDRESS
    ADC #40
    STA $27
    LDA TEXTADDRESS+1
    STA $28
    
    INC $26
    INC $28
    INC $26
    INC $28
    INC $26
    INC $28
    LDY #232
VSCROLLDOWNYS3:
    LDA ($25),Y
    STA ($27),Y
    DEY
    CPY #255
    BNE VSCROLLDOWNYS3

    DEC $26
    DEC $28
    LDX #3
    LDY #255
VSCROLLDOWNYS4:
    LDA ($25),Y
    STA ($27),Y
    DEY
    CPY #255
    BNE VSCROLLDOWNYS4

    DEC $26
    DEC $28
    LDY #255
    DEX
    BNE VSCROLLDOWNYS4
    RTS
