; /*****************************************************************************
;  * ugBASIC - an isomorphic BASIC language compiler for retrocomputers        *
;  *****************************************************************************
;  * Copyright 2021-2025 Marco Spedaletti (asimov@mclink.it)
;  *
;  * Licensed under the Apache License, Version 2.0 (the "License");
;  * you may not use this file except in compliance with the License.
;  * You may obtain a copy of the License at
;  *
;  * http://www.apache.org/licenses/LICENSE-2.0
;  *
;  * Unless required by applicable law or agreed to in writing, software
;  * distributed under the License is distributed on an "AS IS" BASIS,
;  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;  * See the License for the specific language governing permissions and
;  * limitations under the License.
;  *----------------------------------------------------------------------------
;  * Concesso in licenza secondo i termini della Licenza Apache, versione 2.0
;  * (la "Licenza"); è proibito usare questo file se non in conformità alla
;  * Licenza. Una copia della Licenza è disponibile all'indirizzo:
;  *
;  * http://www.apache.org/licenses/LICENSE-2.0
;  *
;  * Se non richiesto dalla legislazione vigente o concordato per iscritto,
;  * il software distribuito nei termini della Licenza è distribuito
;  * "COSì COM'è", SENZA GARANZIE O CONDIZIONI DI ALCUN TIPO, esplicite o
;  * implicite. Consultare la Licenza per il testo specifico che regola le
;  * autorizzazioni e le limitazioni previste dalla medesima.
;  ****************************************************************************/
;* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;*                                                                             *
;*                           IMAGES ROUTINE FOR EF936X                         *
;*                                                                             *
;*                             by Marco Spedaletti                             *
;*                                                                             *
;* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

;--------------

GETIMAGE

@IF vestigialConfig.doubleBufferSelected 

@ELSE

    ; Check if double buffering is active -- in case,
    ; whe should use a different version.
    LDA DOUBLEBUFFERENABLED
    CMPA #0
    LBEQ GETIMAGEORIG

@ENDIF

; ----------------------------------------------
; Version active on double buffering ON
; ----------------------------------------------

@IF !vestigialConfig.doubleBufferSelected || vestigialConfig.doubleBuffer

    ORCC #$50

@IF PC128OP

    PSHS D
    LDA BANKSHADOW
    STA BASE_SEGMENT+$E5
    PULS D

@ENDIF

@IF vestigialConfig.screenModeUnique

@ELSE

GETIMAGEDB
    LDA CURRENTMODE
    CMPA #0
    BNE GETIMAGE0XDB
    JMP GETIMAGE0DB
GETIMAGE0XDB
    CMPA #1
    BNE GETIMAGE1XDB
    JMP GETIMAGE1DB
GETIMAGE1XDB
    CMPA #2
    BNE GETIMAGE2XDB
    JMP GETIMAGE2DB
GETIMAGE2XDB
    CMPA #3
    BNE GETIMAGE3XDB
    JMP GETIMAGE3DB
GETIMAGE3XDB
    CMPA #4
    BNE GETIMAGE4XDB
    JMP GETIMAGE4DB
GETIMAGE4XDB

@IF PC128OP

    PSHS D
    LDA #7
    STA BASE_SEGMENT+$E5
    PULS D

@ENDIF

    ANDCC #$AF

    RTS

@ENDIF

@IF !vestigialConfig.screenModeUnique || ( ( currentMode == 1 ) || ( currentMode == 4 ) )

GETIMAGE1DB
GETIMAGE4DB

@IF PC128OP

    PSHS D
    LDA #7
    STA BASE_SEGMENT+$E5
    PULS D

@ENDIF

    ANDCC #$AF

    RTS

@ENDIF

@IF !vestigialConfig.screenModeUnique || ( ( currentMode == 0 ) || ( currentMode == 2 ) )

GETIMAGE0DB
GETIMAGE2DB

    PSHS Y

    LDX BITMAPADDRESS

    ANDCC #$FE
    LDD <IMAGEY
    STD <IMAGEY2
    LSLB
    ROLA
    LSLB
    ROLA

    LSLB
    ROLA

    TFR D, Y

    ANDCC #$FE
    LDD <IMAGEY
    STD <IMAGEY2
    LSLB
    ROLA
    LSLB
    ROLA

    LSLB
    ROLA
    LSLB
    ROLA
    LSLB
    ROLA

    LEAY D, Y
    TFR Y, D
    LEAX D, X

    ANDCC #$FE
    LDD <IMAGEX
    LSRA
    RORB
    LSRA
    RORB
    LSRA
    RORB
    LEAX D, X

    PULS Y

    ; 128 -> 32768 pixels
    LDD ,Y
    LSRA
    RORB
    LSRA
    RORB
    LSRA
    RORB
    STD <IMAGEW
    STD <IMAGEW2
    LDA 2,Y
    STA <IMAGEH
    STA <IMAGEH2

    LEAY 3,Y

    ; 128 -> 32768 pixels
    LDD <IMAGEW
    PSHS D
    LDB <IMAGEH
    PSHS X,D

    JMP GETIMAGE2YDB

@ENDIF

@IF !vestigialConfig.screenModeUnique || ( ( currentMode == 3 ) )

GETIMAGE3DB

    PSHS Y

    CLRA
    STA <IMAGEY
    STA <IMAGEY2
    LDB <IMAGEY+1
    STB <IMAGEY2+1
    LSLB
    ROLA
    ADDD #PLOTVBASE
    TFR D, X
    LDD , X
    TFR D, X

    CLRA
    STA <(IMAGEX)
    LDB <(IMAGEX+1)
    LSRB
    LSRB
    LEAX B, X

    PULS Y

    ; 128 -> 32768 pixels
    LDD ,Y
    LSRA
    RORB
    LSRA
    RORB
    STD <IMAGEW
    STD <IMAGEW2
    PSHS D
    LDA 2,Y
    STA <IMAGEH
    STA <IMAGEH2

    LEAY 3,Y

    LDA <(IMAGEW+1)
    LDB <IMAGEH
    PSHS X,D

    JMP GETIMAGE2YDB

@ENDIF

GETIMAGE2YDB
GETIMAGE2YDEFDB
    LDA <IMAGEF
    ANDA #64
    BNE GETIMAGE2YDEFDBL128

    LDD <IMAGEW
    CMPD #127
    LBLE GETIMAGE2YDEFDBW128

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; --- ORIGINAL VERSION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

GETIMAGE2YDEFDBL128

    ; LDA BASE_SEGMENT+$c0
    ; ORA #$01
    ; STA BASE_SEGMENT+$c0

@IF PC128OP

    LEAX $8000,X

@ELSE

@ENDIF

    LDD <IMAGEW2
    STD <IMAGEW

GETIMAGE2L1DB000
    LDB <(IMAGEW+1)
    DECB
GETIMAGE2L1DB
    LDA B,X
    STA B,Y
    DECB
    CMPB #0
    BGE GETIMAGE2L1DB

    LDU <IMAGEW
    LEAU -128, U
    STU <IMAGEW
    CMPU #0
    BLE GETIMAGE2L1DB001

    LEAY 128, Y
    LEAX 128, X
    JMP GETIMAGE2L1DB000

GETIMAGE2L1DB001

    LDA <IMAGEF
    ANDA #64
    CMPA #0
    BEQ GETIMAGE2L1DBN

    LDA <IMAGEF
    ANDA #1
    CMPA #1
    BEQ GETIMAGE2L1DBN0

    ORA #65
    STA <IMAGEF

    LDD <IMAGEW2
    STD <IMAGEW
    LDB CURRENTSL
    LEAX B, X
    JMP GETIMAGE2L1DB000

GETIMAGE2L1DBN0
    LDA <IMAGEF
    ANDA #$FE
    STA <IMAGEF

GETIMAGE2L1DBN

    LDD <IMAGEW2
    LEAY D, Y

    LDB CURRENTSL
    LEAX B, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BEQ GETIMAGECOMMONE2DB

    LDD <IMAGEW2
    STD <IMAGEW
    JMP GETIMAGE2L1DB000

GETIMAGECOMMONE2DBA

GETIMAGECOMMONE2DBAY

    LDD <IMAGEW2
    LEAY D, Y
    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BNE GETIMAGECOMMONE2DBAY

GETIMAGECOMMONE2DB

    LDD <IMAGEY2
    STD <IMAGEY

    PULS X,D
    STB <IMAGEH
    PULS D
    STD <IMAGEW

@IF PC128OP

    LEAX $6000,X

@ELSE

    LEAX $2000,X

@ENDIF

    ; LDA BASE_SEGMENT+$c0
    ; ANDA #$fe
    ; STA BASE_SEGMENT+$c0

GETIMAGE2L12DB000
    LDB <(IMAGEW+1)
    DECB
GETIMAGE2L12DB
    LDA B,X
    STA B,Y
    DECB
    CMPB #0
    BGE GETIMAGE2L12DB

    LDU <IMAGEW
    LEAU -128, U
    STU <IMAGEW
    CMPU #0
    BLE GETIMAGE2L12DB001

    LEAY 128, Y
    LEAX 128, X
    JMP GETIMAGE2L12DB000

GETIMAGE2L12DB001

    LDA <IMAGEF
    ANDA #64
    CMPA #0
    BEQ GETIMAGE2L12DBN

    LDA <IMAGEF
    ANDA #1
    CMPA #1
    BEQ GETIMAGE2L12DBN0

    ORA #65
    STA <IMAGEF

    LDD <IMAGEW2
    STD <IMAGEW
    LDB CURRENTSL
    LEAX B, X
    JMP GETIMAGE2L12DB000

GETIMAGE2L12DBN0
    LDA <IMAGEF
    ANDA #$FE
    STA <IMAGEF

GETIMAGE2L12DBN

    LDD <IMAGEW2
    LEAY D, Y

    LDB CURRENTSL
    LEAX B, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    LBEQ GETIMAGECOMMONE5DB

    LDD <IMAGEW2
    STD <IMAGEW
    JMP GETIMAGE2L12DB000

GETIMAGECOMMONE5DBA

GETIMAGECOMMONE5DBAY

    LDD <IMAGEW2
    LEAY D, Y
    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #$0
    BNE GETIMAGECOMMONE5DBAY

GETIMAGECOMMONE5DB

    LDD <IMAGEY2
    STD <IMAGEY

;     LDA CURRENTMODE
;     CMPA #3
;     BEQ GETIMAGECOMMONE53
;     LDU #4
;     JMP GETIMAGECOMMONE50
; GETIMAGECOMMONE53
;     LDU #16
;     JMP GETIMAGECOMMONE50

; GETIMAGECOMMONE50
;     LDA #0
;     STA BASE_SEGMENT+$DB
; GETIMAGECOMMONE50L1
;     LDD ,Y
;     LEAY 2,Y
;     STB BASE_SEGMENT+$DA
;     STA BASE_SEGMENT+$DA
;     LEAU -1, U
;     CMPU #$FFFF
    ; BNE GETIMAGECOMMONE50L1

GETIMAGECOMMONEDB

@IF PC128OP

    PSHS D
    LDA #7
    STA BASE_SEGMENT+$E5
    PULS D

@ENDIF

    ANDCC #$AF
    
	RTS

@ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; --- OPTIMIZED VERSION (w < 128, no double y)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

GETIMAGE2YDEFDBW128

    CMPB #1
    BEQ GETIMAGE2YDEFDBW128EVEN1
    BNE *+5
    JMP GETIMAGE2YDEFDBW128EVEN2
    CMPB #3
    LBEQ GETIMAGE2YDEFDBW128EVEN3
    CMPB #4
    LBEQ GETIMAGE2YDEFDBW128EVEN4

@IF PC128OP

    LEAX $8000,X

@ELSE

@ENDIF

    LDB <(IMAGEW2+1)
    STB <(IMAGEW+1)

GETIMAGE2L1DB000W128
    ; LDB <(IMAGEW+1)
    DECB
GETIMAGE2L1DBW128
    LDA B,X
    STA B,Y
    DECB
    CMPB #0
    BGE GETIMAGE2L1DBW128

GETIMAGE2L1DBNW128

    LDB <(IMAGEW2+1)
    LEAY B, Y

    LDB CURRENTSL
    LEAX B, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BEQ GETIMAGECOMMONE2DBW128

    LDB <(IMAGEW2+1)
    STB <(IMAGEW+1)
    JMP GETIMAGE2L1DB000W128

GETIMAGECOMMONE2DBW128

    LDB <(IMAGEY2+1)
    STB <(IMAGEY+1)

    PULS X,D
    STB <IMAGEH
    PULS D
    STD <IMAGEW

@IF PC128OP

    LEAX $6000,X

@ELSE

    LEAX $2000,X

@ENDIF

    LDB <(IMAGEW+1)

GETIMAGE2L12DB000W128
    DECB
GETIMAGE2L12DBW128
    LDA B,X
    STA B,Y
    DECB
    CMPB #0
    BGE GETIMAGE2L12DBW128

    LDB <(IMAGEW2+1)
    LEAY B, Y

    LDB CURRENTSL
    LEAX B, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    LBEQ GETIMAGECOMMONE5DBW128

    LDB <(IMAGEW2+1)
    STB <(IMAGEW+1)
    JMP GETIMAGE2L12DB000W128

GETIMAGECOMMONE5DBW128

GETIMAGECOMMONEDBW128

@IF PC128OP

    PSHS D
    LDA #7
    STA BASE_SEGMENT+$E5
    PULS D

@ENDIF

    ANDCC #$AF
    
	RTS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; --- OPTIMIZED VERSION (w = 1)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

GETIMAGE2YDEFDBW128EVEN1

    LDA CURRENTSL
    DECA
    STA GETIMAGE2L1DBNW128EVEN1DELTA0+2
    STA GETIMAGE2L1DBNW128EVEN1DELTA1+2

@IF PC128OP

    LEAX $8000,X

@ELSE

@ENDIF

GETIMAGE2L1DB000W128EVEN1
    LDB ,X+
    STB ,Y+

GETIMAGE2L1DBNW128EVEN1

GETIMAGE2L1DBNW128EVEN1DELTA0
    LEAX 42, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BEQ GETIMAGECOMMONE2DBW128EVEN1

    JMP GETIMAGE2L1DB000W128EVEN1

GETIMAGECOMMONE2DBW128EVEN1

    PULS X,D
    STB <IMAGEH
    PULS D

@IF PC128OP

    LEAX $6000,X

@ELSE

    LEAX $2000,X

@ENDIF

GETIMAGE2L12DB000W128EVEN1
    LDB ,X+
    STB ,Y+

GETIMAGE2L1DBNW128EVEN1DELTA1
    LEAX 42, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BEQ GETIMAGECOMMONE5DBW128EVEN1

    BRA GETIMAGE2L12DB000W128EVEN1

GETIMAGECOMMONE5DBW128EVEN1
GETIMAGECOMMONEDBW128EVEN1

    JMP GETIMAGECOMMONEDBW128EVENFINAL

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; --- OPTIMIZED VERSION (w = 2)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

GETIMAGE2YDEFDBW128EVEN2

    LDA CURRENTSL
    DECA
    DECA
    STA GETIMAGE2L1DBNW128EVEN2DELTA0+2
    STA GETIMAGE2L1DBNW128EVEN2DELTA1+2

@IF PC128OP

    LEAX $8000,X

@ELSE

@ENDIF

GETIMAGE2L1DB000W128EVEN2
    LDD ,X++
    STD ,Y++

GETIMAGE2L1DBNW128EVEN2

GETIMAGE2L1DBNW128EVEN2DELTA0
    LEAX 42, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BNE GETIMAGE2L1DB000W128EVEN2

GETIMAGECOMMONE2DBW128EVEN2

    PULS X,D
    STB <IMAGEH
    PULS D

@IF PC128OP

    LEAX $6000,X

@ELSE

    LEAX $2000,X

@ENDIF

GETIMAGE2L12DB000W128EVEN2
    LDD ,X++
    STD ,Y++
    
GETIMAGE2L1DBNW128EVEN2DELTA1
    LEAX 42, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BNE GETIMAGE2L12DB000W128EVEN2

GETIMAGECOMMONE5DBW128EVEN2
GETIMAGECOMMONEDBW128EVEN2

    JMP GETIMAGECOMMONEDBW128EVENFINAL

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; --- OPTIMIZED VERSION (w = 3, even lines)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

GETIMAGE2YDEFDBW128EVEN3EVEN

    LDA CURRENTSL
    DECA
    DECA
    DECA
    STA GETIMAGE2YDEFDBW128EVEN3EVENDELTA0+2
    STA GETIMAGE2YDEFDBW128EVEN3EVENDELTA1+2
    STA GETIMAGE2YDEFDBW128EVEN3EVENDELTA2+2
    STA GETIMAGE2YDEFDBW128EVEN3EVENDELTA3+2

@IF PC128OP

    LEAX $8000,X

@ELSE

@ENDIF

GETIMAGE2YDEFDBW128EVEN3EVEN3
    LDD ,X++
    STD ,Y++
    LDA ,X+
    STA ,Y+
GETIMAGE2YDEFDBW128EVEN3EVENDELTA0
    LEAX 42, X
    LDD ,X++
    STD ,Y++
    LDA ,X+
    STA ,Y+
GETIMAGE2YDEFDBW128EVEN3EVENDELTA1
    LEAX 42, X

    DEC <IMAGEH
    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BEQ GETIMAGECOMMONE2DBW128EVEN3EVEN3

    JMP GETIMAGE2YDEFDBW128EVEN3EVEN3

GETIMAGECOMMONE2DBW128EVEN3EVEN3

    PULS X,D
    STB <IMAGEH
    PULS D

@IF PC128OP

    LEAX $6000,X

@ELSE

    LEAX $2000,X

@ENDIF

GETIMAGE2L12DB000W128EVEN3EVEN3
    LDD ,X++
    STD ,Y++
    LDA ,X+
    STA ,Y+
GETIMAGE2YDEFDBW128EVEN3EVENDELTA2
    LEAX 42, X
    LDD ,X++
    STD ,Y++
    LDA ,X+
    STA ,Y+
GETIMAGE2YDEFDBW128EVEN3EVENDELTA3
    LEAX 42, X

    DEC <IMAGEH
    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BEQ GETIMAGECOMMONEDBW128EVEN3EVEN

    JMP GETIMAGE2L12DB000W128EVEN3EVEN3

GETIMAGECOMMONE5DBW128EVEN3EVEN
GETIMAGECOMMONEDBW128EVEN3EVEN

    JMP GETIMAGECOMMONEDBW128EVENFINAL

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; --- OPTIMIZED VERSION (w = 3)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

GETIMAGE2YDEFDBW128EVEN3
    
    LSRA
    BCC GETIMAGE2YDEFDBW128EVEN3EVEN

    LDA CURRENTSL
    DECA
    DECA
    DECA
    STA GETIMAGE2L1DBNW128EVEN3DELTA0+2
    STA GETIMAGE2L1DBNW128EVEN3DELTA1+2
    LDA <IMAGEH


@IF PC128OP

    LEAX $8000,X

@ELSE

@ENDIF

GETIMAGE2L1DB000W128EVEN3
    LDD ,X++
    STD ,Y++
    LDA ,X+
    STA ,Y+

GETIMAGE2L1DBNW128EVEN3DELTA0
    LEAX 42, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BEQ GETIMAGECOMMONE2DBW128EVEN3

    JMP GETIMAGE2L1DB000W128EVEN3

GETIMAGECOMMONE2DBW128EVEN3

    PULS X,D
    STB <IMAGEH
    PULS D

@IF PC128OP

    LEAX $6000,X

@ELSE

    LEAX $2000,X

@ENDIF

GETIMAGE2L12DB000W128EVEN3
    LDD ,X++
    STD ,Y++
    LDA ,X+
    STA ,Y+
    
GETIMAGE2L1DBNW128EVEN3DELTA1
    LEAX 42, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    LBEQ GETIMAGECOMMONE5DBW128EVEN3

    JMP GETIMAGE2L12DB000W128EVEN3

GETIMAGECOMMONE5DBW128EVEN3
GETIMAGECOMMONEDBW128EVEN3

    JMP GETIMAGECOMMONEDBW128EVENFINAL

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; --- OPTIMIZED VERSION (w = 4)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

GETIMAGE2YDEFDBW128EVEN4

    LDA CURRENTSL
    DECA
    DECA
    DECA
    DECA
    STA GETIMAGE2L1DBNW128EVEN4DELTA0+2
    STA GETIMAGE2L1DBNW128EVEN4DELTA1+2
    STA <MATHPTR0

    LDA <IMAGEH
    CMPA #16
    BEQ GETIMAGE2YDEFDBW128EVEN4HX
    CMPA #8
    BEQ GETIMAGE2YDEFDBW128EVEN4HX
    CMPA #4
    BEQ GETIMAGE2YDEFDBW128EVEN4HX

@IF PC128OP

    LEAX $8000,X

@ELSE

@ENDIF

GETIMAGE2L1DB000W128EVEN4
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++

GETIMAGE2L1DBNW128EVEN4

GETIMAGE2L1DBNW128EVEN4DELTA0
    LEAX 42, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BEQ GETIMAGECOMMONE2DBW128EVEN4

    JMP GETIMAGE2L1DB000W128EVEN4

GETIMAGECOMMONE2DBW128EVEN4

    LDB <(IMAGEY2+1)
    STB <(IMAGEY+1)

    PULS X,D
    STB <IMAGEH
    PULS D

@IF PC128OP

    LEAX $6000,X

@ELSE

    LEAX $2000,X

@ENDIF

GETIMAGE2L12DB000W128EVEN4
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    
GETIMAGE2L1DBNW128EVEN4DELTA1
    LEAX 42, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    LBEQ GETIMAGECOMMONE5DBW128EVEN4

    JMP GETIMAGE2L12DB000W128EVEN4

GETIMAGECOMMONE5DBW128EVEN4
GETIMAGECOMMONEDBW128EVEN4

    JMP GETIMAGECOMMONEDBW128EVENFINAL

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; --- OPTIMIZED VERSION (w = 4, h = 16, 8, 4)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

GETIMAGE2YDEFDBW128EVEN4HX

@IF PC128OP

    LEAX $8000,X

@ELSE

@ENDIF

    CMPA #8
    BEQ GETIMAGE2L1DB000W128EVEN4H8
    CMPA #4
    LBEQ GETIMAGE2L1DB000W128EVEN4H4

GETIMAGE2L1DB000W128EVEN4H16
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
GETIMAGE2L1DB000W128EVEN4H8
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
GETIMAGE2L1DB000W128EVEN4H4
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++

    LDB <(IMAGEY2+1)
    STB <(IMAGEY+1)

    PULS X,D
    STB <IMAGEH
    PULS D

@IF PC128OP

    LEAX $6000,X

@ELSE

    LEAX $2000,X

@ENDIF

    LDA <IMAGEH
    CMPA #8
    BEQ GETIMAGE2L1DB000W128EVEN4H8A
    CMPA #4
    LBEQ GETIMAGE2L1DB000W128EVEN4H4A

GETIMAGE2L1DB000W128EVEN4H16A
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
GETIMAGE2L1DB000W128EVEN4H8A
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
GETIMAGE2L1DB000W128EVEN4H4A
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++
    LDA <MATHPTR0
    LEAX A, X
    LDD ,X++
    STD ,Y++
    LDD ,X++
    STD ,Y++

    JMP GETIMAGECOMMONEDBW128EVENFINAL

GETIMAGECOMMONEDBW128EVENFINAL

@IF PC128OP

    PSHS D
    LDA #7
    STA BASE_SEGMENT+$E5
    PULS D

@ENDIF

    ANDCC #$AF
    
	RTS

; ----------------------------------------------
; Version active on double buffering OFF
; ----------------------------------------------

@IF !vestigialConfig.doubleBufferSelected || !vestigialConfig.doubleBuffer

GETIMAGEORIG

@IF vestigialConfig.screenModeUnique

@ELSE

    LDA CURRENTMODE
    CMPA #0
    BNE GETIMAGE0X
    JMP GETIMAGE0
GETIMAGE0X
    CMPA #1
    BNE GETIMAGE1X
    JMP GETIMAGE1
GETIMAGE1X
    CMPA #2
    BNE GETIMAGE2X
    JMP GETIMAGE2
GETIMAGE2X
    CMPA #3
    BNE GETIMAGE3X
    JMP GETIMAGE3
GETIMAGE3X
    CMPA #4
    BNE GETIMAGE4X
    JMP GETIMAGE4
GETIMAGE4X
    RTS

@ENDIF

@IF !vestigialConfig.screenModeUnique || ( ( currentMode == 1 ) || ( currentMode == 4 ) )

GETIMAGE1
GETIMAGE4
    RTS

@ENDIF

@IF !vestigialConfig.screenModeUnique || ( ( currentMode == 0 ) || ( currentMode == 2 ) )

GETIMAGE0
GETIMAGE2

    PSHS Y

    LDX BITMAPADDRESS

    ANDCC #$FE
    LDD <IMAGEY
    STD <IMAGEY2
    LSLB
    ROLA
    LSLB
    ROLA

    LSLB
    ROLA

    TFR D, Y

    ANDCC #$FE
    LDD <IMAGEY
    STD <IMAGEY2
    LSLB
    ROLA
    LSLB
    ROLA

    LSLB
    ROLA
    LSLB
    ROLA
    LSLB
    ROLA

    LEAY D, Y
    TFR Y, D
    LEAX D, X

    ANDCC #$FE
    LDD <IMAGEX
    LSRA
    RORB
    LSRA
    RORB
    LSRA
    RORB
    LEAX D, X

    PULS Y

    LDA ,Y
    LDB 1,Y
    LSRA
    RORB
    LSRA
    RORB
    LSRA
    RORB
    STD <IMAGEW
    STD <IMAGEW2
    LDA 2,Y
    STA <IMAGEH
    STA <IMAGEH2

    LEAY 3,Y

    LDD <IMAGEW
    PSHS D
    LDB <IMAGEH
    PSHS X,D

    JMP GETIMAGE2Y

@ENDIF

@IF !vestigialConfig.screenModeUnique || ( ( currentMode == 3 ) )

GETIMAGE3

    PSHS Y

    CLRA
    LDB <IMAGEY+1
    STB <IMAGEY2+1
    LSLB
    ROLA
    ADDD #PLOTVBASE
    TFR D, X
    LDD , X
@IF TO8
    ADDD BITMAPADDRESS
@ENDIF
    TFR D, X

    LDB <(IMAGEX+1)
    LSRB
    LSRB
    LEAX B, X

    PULS Y

    LDA ,Y
    LDB 1,Y
    LSRA
    RORB
    LSRA
    RORB
    STD <IMAGEW
    STD <IMAGEW2
    LDA 2,Y
    STA <IMAGEH
    STA <IMAGEH2

    LEAY 3,Y

    LDD <IMAGEW
    PSHS D
    LDB <IMAGEH
    PSHS X,D

    JMP GETIMAGE2Y

@ENDIF

GETIMAGE2Y
GETIMAGE2YDEF

@IF TO8

    LDA BASE_SEGMENT+$c3
    ORA #$01
    STA BASE_SEGMENT+$c3

@ELSE

    LDA BASE_SEGMENT+$c0
    ORA #$01
    STA BASE_SEGMENT+$c0

@ENDIF

    LDD <IMAGEW2
    STD <IMAGEW
GETIMAGE2L1000
    LDB <(IMAGEW+1)
    DECB
GETIMAGE2L1
    LDA B,X
    STA B,Y
    DECB
    CMPB #0
    BGE GETIMAGE2L1

    LDU <IMAGEW
    LEAU -128, U
    STU <IMAGEW
    CMPU #0
    BLE GETIMAGE2L1001

    LEAY 128, Y
    LEAX 128, X
    JMP GETIMAGE2L1000

GETIMAGE2L1001

    LDA <IMAGEF
    ANDA #64
    CMPA #0
    BEQ GETIMAGE2L1N

    LDA <IMAGEF
    ANDA #1
    CMPA #1
    BEQ GETIMAGE2L1N0

    ORA #65
    STA <IMAGEF

    LDD <IMAGEW2
    STD <IMAGEW
    LDB CURRENTSL
    LEAX B, X
    JMP GETIMAGE2L1000

GETIMAGE2L1N0
    LDA <IMAGEF
    ANDA #$FE
    STA <IMAGEF

GETIMAGE2L1N

    LDD <IMAGEW2
    LEAY D, Y

    LDB CURRENTSL
    LEAX B, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BEQ GETIMAGECOMMONE2

    LDD <IMAGEW2
    STD <IMAGEW
    JMP GETIMAGE2L1000

GETIMAGECOMMONE2A

GETIMAGECOMMONE2AY

    LDD <IMAGEW2
    LEAY D, Y
    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #$0
    BNE GETIMAGECOMMONE2AY

GETIMAGECOMMONE2

    LDD <IMAGEY2
    STD <IMAGEY

    PULS X,D
    STB <IMAGEH
    PULS D
    STD <IMAGEW

@IF TO8

    LDA BASE_SEGMENT+$c3
    ANDA #$fe
    STA BASE_SEGMENT+$c3

@ELSE

    LDA BASE_SEGMENT+$c0
    ANDA #$fe
    STA BASE_SEGMENT+$c0

@ENDIF

    LDD <IMAGEW2
    STD <IMAGEW
GETIMAGE2L12000
    LDB <(IMAGEW+1)
    DECB
GETIMAGE2L12
    LDA B,X
    STA B,Y
    DECB
    CMPB #0
    BGE GETIMAGE2L12

    LDU <IMAGEW
    LEAU -128, U
    STU <IMAGEW
    CMPU #0
    BLE GETIMAGE2L12001

    LEAY 128, Y
    LEAX 128, X
    JMP GETIMAGE2L12000

GETIMAGE2L12001

    LDA <IMAGEF
    ANDA #64
    CMPA #0
    BEQ GETIMAGE2L12N

    LDA <IMAGEF
    ANDA #1
    CMPA #1
    BEQ GETIMAGE2L12N0

    ORA #65
    STA <IMAGEF

    LDD <IMAGEW2
    STD <IMAGEW
    LDB CURRENTSL
    LEAX B, X
    JMP GETIMAGE2L12000

GETIMAGE2L12N0
    LDA <IMAGEF
    ANDA #$FE
    STA <IMAGEF

GETIMAGE2L12N

    LDD <IMAGEW2
    LEAY D, Y

    LDB CURRENTSL
    LEAX B, X

    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BEQ GETIMAGECOMMONE5

    LDD <IMAGEW2
    STD <IMAGEW
    JMP GETIMAGE2L12000

GETIMAGECOMMONE5A

GETIMAGECOMMONE5AY

    LDD <IMAGEW2
    LEAY D, Y
    DEC <IMAGEH
    LDB <IMAGEH
    CMPB #0
    BNE GETIMAGECOMMONE5AY

GETIMAGECOMMONE5

    LDD <IMAGEY2
    STD <IMAGEY

;     LDA CURRENTMODE
;     CMPA #3
;     BEQ GETIMAGECOMMONE53
;     LDU #4
;     JMP GETIMAGECOMMONE50
; GETIMAGECOMMONE53
;     LDU #16
;     JMP GETIMAGECOMMONE50

; GETIMAGECOMMONE50
;     LDA #0
;     STA BASE_SEGMENT+$DB
; GETIMAGECOMMONE50L1
;     LDD ,Y
;     LEAY 2,Y
;     STB BASE_SEGMENT+$DA
;     STA BASE_SEGMENT+$DA
;     LEAU -1, U
;     CMPU #$FFFF
    ; BNE GETIMAGECOMMONE50L1

GETIMAGECOMMONE
    RTS

@ENDIF
