; CCGMS Terminal
;
; Copyright (c) 2016,2022, Craig Smith, alwyz, Michael Steil. All rights reserved.
; This project is licensed under the BSD 3-Clause License.
;
; C64 Hardware Constants
;

; CIA#1 I/O
cia1talo	= $dc04
cia1tahi	= $dc05
cia1tblo	= $dc06
cia1tbhi	= $dc07
cia1sdr         = $dc0c
cia1icr         = $dc0d
cia1cra         = $dc0e
cia1crb         = $dc0f
; CIA#2 I/O
cia2pa		= $dd00
cia2pb		= $dd01
cia2ddrb	= $dd03
cia2tblo	= $dd06
cia2tbhi	= $dd07
cia2sdr         = $dd0c
cia2icr         = $dd0d
cia2crb         = $dd0f
