 DO
    IF JLEFT(1) THEN : PRINT "WEST" : ENDIF
    IF JRIGHT(1) THEN : PRINT "EAST" : ENDIF
    IF JUP(1) THEN : PRINT "NORTH" : ENDIF
    IF JDOWN(1) THEN : PRINT "SOUTH" : ENDIF
    IF JFIRE(1) THEN : CENTRE "BANG!" : ENDIF
 LOOP
