    CLS
    LOCATE 10,10
    PRINT "HELLO WORLD!";

    LOCATE 10,10
    HSCROLL LEFT
    REM WAIT 1000 MS
    REM HSCROLL RIGHT
    REM WAIT 1000 MS

    REM HSCROLL SCREEN LEFT
    REM WAIT 1000 MS
    REM HSCROLL SCREEN RIGHT
    REM WAIT 1000 MS

    HALT