    CLS
    LOCATE 10,10
    PRINT "HELLO WORLD!";

    LOCATE 10,10
    HSCROLL LEFT
    WAIT 1000 MS
    HSCROLL RIGHT
    WAIT 1000 MS

    HSCROLL SCREEN LEFT
    WAIT 1000 MS
    HSCROLL SCREEN RIGHT
    WAIT 1000 MS

    HALT