    CLS

    LOCATE 0,1
    PRINT "FIRST LINE!";

    LOCATE 10,10
    PRINT "HELLO WORLD!";

    LOCATE 10,10
    VSCROLL SCREEN UP
    WAIT 1000 MS
    VSCROLL SCREEN DOWN
    VSCROLL SCREEN DOWN
    VSCROLL SCREEN DOWN
    WAIT 1000 MS

    HALT