; /*****************************************************************************
;  * ugBASIC - an isomorphic BASIC language compiler for retrocomputers        *
;  *****************************************************************************
;  * Copyright 2021-2025 Marco Spedaletti (asimov@mclink.it)
;  *
;  * Licensed under the Apache License, Version 2.0 (the "License");
;  * you may not use this file eXcept in compliance with the License.
;  * You may obtain a copy of the License at
;  *
;  * http://www.apache.org/licenses/LICENSE-2.0
;  *
;  * Unless required by applicable law or agreed to in writing, software
;  * distributed under the License is distributed on an "AS IS" BASIS,
;  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either eXpress or implied.
;  * See the License for the specific language governing permissions and
;  * limitations under the License.
;  *----------------------------------------------------------------------------
;  * Concesso in licenza secondo i termini della Licenza Apache, versione 2.0
;  * (la "Licenza"); è proibito usare questo file se non in conformità alla
;  * Licenza. Una copia della Licenza è disponibile all'indirizzo:
;  *
;  * http://www.apache.org/licenses/LICENSE-2.0
;  *
;  * Se non richiesto dalla legislazione vigente o concordato per iscritto,
;  * il software distribuito nei termini della Licenza è distribuito
;  * "COSì COM'è", SENZA GARANZIE O CONDIZIONI DI ALCUN TIPO, esplicite o
;  * implicite. Consultare la Licenza per il testo specifico che regola le
;  * autorizzazioni e le limitazioni previste dalla medesima.
;  ****************************************************************************/
;* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;*                                                                             *
;*                           MUSIC PLAYER ROUTINE ON SID                       *
;*                                                                             *
;*                             by Marco Spedaletti                             *
;*                                                                             *
;* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

WAVEFORM_TRIANGLE                           = $10
WAVEFORM_SAW                                = $20
WAVEFORM_RECTANGLE                          = $40
WAVEFORM_NOISE                              = $80

IMF_TOKEN_WAIT1								= $ff
IMF_TOKEN_WAIT2								= $fe
IMF_TOKEN_CONTROL							= $d0
IMF_TOKEN_PROGRAM_CHANGE					= $e0
IMF_TOKEN_NOTE								= $40

IMF_INSTRUMENT_ACOUSTIC_GRAND_PIANO			= $01
IMF_INSTRUMENT_BRIGHT_ACOUSTIC_PIANO		= $02
IMF_INSTRUMENT_ELECTRIC_GRAND_PIANO			= $03
IMF_INSTRUMENT_HONKY_TONK_PIANO				= $04
IMF_INSTRUMENT_ELECTRIC_PIANO1				= $05
IMF_INSTRUMENT_ELECTRIC_PIANO2				= $06
IMF_INSTRUMENT_HARPSICHORD					= $07
IMF_INSTRUMENT_CLAVI						= $08

IMF_INSTRUMENT_CELESTA						= $09
IMF_INSTRUMENT_GLOCKENSPIEL					= $0A
IMF_INSTRUMENT_MUSIC_BOX					= $0B
IMF_INSTRUMENT_VIBRAPHONE					= $0C
IMF_INSTRUMENT_MARIMBA						= $0D
IMF_INSTRUMENT_XYLOPHONE					= $0E
IMF_INSTRUMENT_TUBULAR_BELLS				= $0F
IMF_INSTRUMENT_DULCIMER						= $10
IMF_INSTRUMENT_DRAWBAR_ORGAN				= $11
IMF_INSTRUMENT_PERCUSSIVE_ORGAN				= $12
IMF_INSTRUMENT_ROCK_ORGAN					= $13
IMF_INSTRUMENT_CHURCH_ORGAN					= $14
IMF_INSTRUMENT_REED_ORGAN					= $15
IMF_INSTRUMENT_ACCORDION					= $16
IMF_INSTRUMENT_HARMONICA					= $17
IMF_INSTRUMENT_TANGO_ACCORDION				= $18
IMF_INSTRUMENT_ACOUSTIC_GUITAR_NYLON			= $19
IMF_INSTRUMENT_ACOUSTIC_GUITAR_STEEL			= $1A
IMF_INSTRUMENT_ELECTRIC_GUITAR_JAZZ			= $1B
IMF_INSTRUMENT_ELECTRIC_GUITAR_CLEAN			= $1C
IMF_INSTRUMENT_ELECTRIC_GUITAR_MUTED			= $1D
IMF_INSTRUMENT_OVERDRIVEN_GUITAR			= $1E
IMF_INSTRUMENT_DISTORTION_GUITAR			= $1F
IMF_INSTRUMENT_GUITAR_HARMONICS				= $20
IMF_INSTRUMENT_ACOUSTIC_BASS				= $21
IMF_INSTRUMENT_ELECTRIC_BASS_FINGER			= $22
IMF_INSTRUMENT_ELECTRIC_BASS_PICK			= $23
IMF_INSTRUMENT_FRETLESS_BASS				= $24
IMF_INSTRUMENT_SLAP_BASS_1					= $25
IMF_INSTRUMENT_SLAP_BASS_2					= $26
IMF_INSTRUMENT_SYNTH_BASS_1					= $27
IMF_INSTRUMENT_SYNTH_BASS_2					= $28
IMF_INSTRUMENT_VIOLIN						= $29
IMF_INSTRUMENT_VIOLA						= $2A
IMF_INSTRUMENT_CELLO						= $2B
IMF_INSTRUMENT_CONTRABASS					= $2C
IMF_INSTRUMENT_TREMOLO_STRINGS				= $2D
IMF_INSTRUMENT_PIZZICATO_STRINGS			= $2E
IMF_INSTRUMENT_ORCHESTRAL_HARP				= $2F
IMF_INSTRUMENT_TIMPANI						= $30
IMF_INSTRUMENT_STRING_ENSEMBLE_1			= $31
IMF_INSTRUMENT_STRING_ENSEMBLE_2			= $32
IMF_INSTRUMENT_SYNTHSTRINGS_1				= $33
IMF_INSTRUMENT_SYNTHSTRINGS_2				= $34
IMF_INSTRUMENT_CHOIR_AAHS					= $35
IMF_INSTRUMENT_VOICE_OOHS					= $36
IMF_INSTRUMENT_SYNTH_VOICE					= $37
IMF_INSTRUMENT_ORCHESTRA_HIT				= $38
IMF_INSTRUMENT_TRUMPET						= $39
IMF_INSTRUMENT_TROMBONE						= $3A
IMF_INSTRUMENT_TUBA							= $3B
IMF_INSTRUMENT_MUTED_TRUMPET				= $3C
IMF_INSTRUMENT_FRENCH_HORN					= $3D
IMF_INSTRUMENT_BRASS_SECTION				= $3E
IMF_INSTRUMENT_SYNTHBRASS_1					= $3F
IMF_INSTRUMENT_SYNTHBRASS_2					= $40
IMF_INSTRUMENT_SOPRANO_SAX					= $41
IMF_INSTRUMENT_ALTO_SAX						= $42
IMF_INSTRUMENT_TENOR_SAX					= $43
IMF_INSTRUMENT_BARITONE_SAX					= $44
IMF_INSTRUMENT_OBOE							= $45
IMF_INSTRUMENT_ENGLISH_HORN					= $46
IMF_INSTRUMENT_BASSOON						= $47
IMF_INSTRUMENT_CLARINET						= $48
IMF_INSTRUMENT_PICCOLO						= $49
IMF_INSTRUMENT_FLUTE						= $4A
IMF_INSTRUMENT_RECORDER						= $4B
IMF_INSTRUMENT_PAN_FLUTE					= $4C
IMF_INSTRUMENT_BLOWN_BOTTLE					= $4D
IMF_INSTRUMENT_SHAKUHACHI					= $4E
IMF_INSTRUMENT_WHISTLE						= $4F
IMF_INSTRUMENT_OCARINA						= $50
IMF_INSTRUMENT_LEAD_1_SQUARE				= $51
IMF_INSTRUMENT_LEAD_2_SAWTOOTH				= $52
IMF_INSTRUMENT_LEAD_3_CALLIOPE				= $53
IMF_INSTRUMENT_LEAD_4_CHIFF					= $54
IMF_INSTRUMENT_LEAD_5_CHARANG				= $55
IMF_INSTRUMENT_LEAD_6_VOICE					= $56
IMF_INSTRUMENT_LEAD_7_FIFTHS				= $57
IMF_INSTRUMENT_LEAD_8_BASS_LEAD				= $58
IMF_INSTRUMENT_PAD_1_NEW_AGE				= $59
IMF_INSTRUMENT_PAD_2_WARM					= $5A
IMF_INSTRUMENT_PAD_3_POLYSYNTH				= $5B
IMF_INSTRUMENT_PAD_4_CHOIR					= $5C
IMF_INSTRUMENT_PAD_5_BOWED					= $5D
IMF_INSTRUMENT_PAD_6_METALLIC				= $5E
IMF_INSTRUMENT_PAD_7_HALO					= $5F
IMF_INSTRUMENT_PAD_8_SWEEP					= $60
IMF_INSTRUMENT_FX_1_RAIN					= $61
IMF_INSTRUMENT_FX_2_SOUNDTRACK				= $62
IMF_INSTRUMENT_FX_3_CRYSTAL					= $63
IMF_INSTRUMENT_FX_4_ATMOSPHERE				= $64
IMF_INSTRUMENT_FX_5_BRIGHTNESS				= $65
IMF_INSTRUMENT_FX_6_GOBLINS					= $66
IMF_INSTRUMENT_FX_7_ECHOES					= $67
IMF_INSTRUMENT_FX_8_SCI_FI					= $68
IMF_INSTRUMENT_SITAR						= $69
IMF_INSTRUMENT_BANJO						= $6A
IMF_INSTRUMENT_SHAMISEN						= $6B
IMF_INSTRUMENT_KOTO							= $6C
IMF_INSTRUMENT_KALIMBA						= $6D
IMF_INSTRUMENT_BAG_PIPE						= $6E
IMF_INSTRUMENT_FIDDLE						= $6F
IMF_INSTRUMENT_SHANAI						= $70
IMF_INSTRUMENT_TINKLE_BELL					= $71
IMF_INSTRUMENT_AGOGO						= $72
IMF_INSTRUMENT_STEEL_DRUMS					= $73
IMF_INSTRUMENT_WOODBLOCK					= $74
IMF_INSTRUMENT_TAIKO_DRUM					= $75
IMF_INSTRUMENT_MELODIC_TOM					= $76
IMF_INSTRUMENT_SYNTH_DRUM					= $77
IMF_INSTRUMENT_REVERSE_CYMBAL				= $78
IMF_INSTRUMENT_GUITAR_FRET_NOISE			= $79
IMF_INSTRUMENT_BREATH_NOISE					= $7A
IMF_INSTRUMENT_SEASHORE						= $7B
IMF_INSTRUMENT_BIRD_TWEET					= $7C
IMF_INSTRUMENT_TELEPHONE_RING				= $7D
IMF_INSTRUMENT_HELICOPTER					= $7E
IMF_INSTRUMENT_APPLAUSE						= $7F
IMF_INSTRUMENT_GUNSHOT						= $80

MUSICTMP:           DEFB 0

; X: CHANNEL
SIDEXPLOSION:
    LD A, C
    LD C, WAVEFORM_NOISE
    CALL SIDPROGCTR
    LD C, 2
    LD B, 11
    CALL SIDPROGAD
    LD C, 0
    LD B, 1
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDGUNSHOT:
    LD A, C
    LD C, WAVEFORM_NOISE
    CALL SIDPROGCTR
    LD C, 2
    LD B, 4
    CALL SIDPROGAD
    LD C, 0
    LD B, 1
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDPIANO:
SIDCLAVI:
    LD A, C
    LD C, $00
    LD B, $06
    CALL SIDPROGPULSE
    LD C, 2
    LD B, 11
    CALL SIDPROGAD
    LD C, 5
    LD B, 0
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDXYLOPHONE:
    LD A, C
    LD C, $00
    LD B, $06
    CALL SIDPROGPULSE    
    LD C, 0
    LD B, 9
    CALL SIDPROGAD
    LD C, 0
    LD B, 0
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDROCKORGAN:
    LD A, C
    LD C, $00
    LD B, $08
    CALL SIDPROGPULSE
    CALL SIDPROGCTR
    LD C, 0
    LD B, 9
    CALL SIDPROGAD
    LD C, 9
    LD B, 0
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDGUITAR:
SIDBANJO:
    LD A, C
    LD C, WAVEFORM_SAW
    CALL SIDPROGCTR
    LD C, 0
    LD B, 9
    CALL SIDPROGAD
    LD C, 2
    LD B, 1
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDGUITARMUTED:
SIDBASS:
    LD A, C
    LD C, WAVEFORM_SAW
    CALL SIDPROGCTR
    LD C, 0
    LD B, 9
    CALL SIDPROGAD
    LD C, 1
    LD B, 1
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDVIOLIN:
    LD A, C
    LD C, WAVEFORM_TRIANGLE + WAVEFORM_RECTANGLE
    CALL SIDPROGCTR
    LD C, 128
    LD B, 0
    CALL SIDPROGPULSE
    LD C, 10
    LD B, 8
    CALL SIDPROGAD
    LD C, 10
    LD B, 9
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDTIMPANI:
SIDDRUMS:
    LD A, C
    LD C, WAVEFORM_NOISE
    CALL SIDPROGCTR
    LD C, 0
    LD B, 5
    CALL SIDPROGAD
    LD C, 0
    LD B, 0
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDTRUMPET:
    LD A, C
    LD C, WAVEFORM_SAW
    CALL SIDPROGCTR
    LD C, 8
    LD B, 9
    CALL SIDPROGAD
    LD C, 4
    LD B, 1
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDFLUTE:
    LD A, C
    LD C, WAVEFORM_TRIANGLE
    CALL SIDPROGCTR
    LD C, 9
    LD B, 4
    CALL SIDPROGAD
    LD C, 4
    LD B, 0
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDACCORDION:
    LD A, C
    LD C, WAVEFORM_SAW
    CALL SIDPROGCTR
    LD C, 9
    LD B, 4
    CALL SIDPROGAD
    LD C, 4
    LD B, 0
    CALL SIDPROGSR
    RET

; X: CHANNEL
SIDCALLIOPE:
    LD A, C
    LD C, WAVEFORM_TRIANGLE
    CALL SIDPROGCTR
    LD C, 0
    LD B, 0
    CALL SIDPROGAD
    LD C, 15
    LD B, 0
    CALL SIDPROGSR
    RET

; A: PROGRAM, X: CHANNEL
SIDSETPROGRAM:

; General MIDI Level 1 Instrument Families
; The General MIDI Level 1 instrument sounds are grouped by families. 
; In each family are 8 specific instruments.

; 0 special -> drums!

SIDSETPROGRAM0:
    CP 0
    JR NZ, SIDSETPROGRAM1
    CALL SIDDRUMS
    JP SIDSETPROGRAMNN

; 1-8	Piano

SIDSETPROGRAM1:
    DEC A
    JR NZ, SIDSETPROGRAM2
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ACOUSTIC_GRAND_PIANO			= $01
SIDSETPROGRAM2:
    DEC A
    JR NZ, SIDSETPROGRAM3
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_BRIGHT_ACOUSTIC_PIANO			= $02
SIDSETPROGRAM3:
    DEC A
    JR NZ, SIDSETPROGRAM4
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ELECTRIC_GRAND_PIANO			= $03
SIDSETPROGRAM4:
    DEC A
    JR NZ, SIDSETPROGRAM5
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_HONKY_TONK_PIANO				= $04
SIDSETPROGRAM5:
    DEC A
    JR NZ, SIDSETPROGRAM6
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ELECTRIC_PIANO1				= $05
SIDSETPROGRAM6:
    DEC A
    JR NZ, SIDSETPROGRAM7
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ELECTRIC_PIANO2				= $06
SIDSETPROGRAM7:
    DEC A
    JR NZ, SIDSETPROGRAM8
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_HARPSICHORD					= $07
SIDSETPROGRAM8:
    DEC A
    JR NZ, SIDSETPROGRAM9
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_CLAVI						= $08


SIDSETPROGRAM9:
    DEC A
    JR NZ, SIDSETPROGRAMA
    CALL SIDCLAVI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_CELESTA						= $09
SIDSETPROGRAMA:
    DEC A
    JR NZ, SIDSETPROGRAMB
    CALL SIDXYLOPHONE
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_GLOCKENSPIEL					= $0A
SIDSETPROGRAMB:
    DEC A
    JR NZ, SIDSETPROGRAMC
    CALL SIDXYLOPHONE
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_MUSIC_BOX					= $0B
SIDSETPROGRAMC:
    DEC A
    JR NZ, SIDSETPROGRAMD
    CALL SIDXYLOPHONE
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_VIBRAPHONE					= $0C
SIDSETPROGRAMD:
    DEC A
    JR NZ, SIDSETPROGRAME
    CALL SIDXYLOPHONE
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_MARIMBA						= $0D
SIDSETPROGRAME:
    DEC A
    JR NZ, SIDSETPROGRAMF
    CALL SIDXYLOPHONE
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_XYLOPHONE					= $0E
SIDSETPROGRAMF:
    DEC A
    JR NZ, SIDSETPROGRAM10
    CALL SIDXYLOPHONE
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TUBULAR_BELLS				= $0F
SIDSETPROGRAM10:
    DEC A
    JR NZ, SIDSETPROGRAM11
    CALL SIDXYLOPHONE
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_DULCIMER						= $10
SIDSETPROGRAM11:
    DEC A
    JR NZ, SIDSETPROGRAM12
    CALL SIDROCKORGAN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_DRAWBAR_ORGAN				= $11
SIDSETPROGRAM12:
    DEC A
    JR NZ, SIDSETPROGRAM13
    CALL SIDROCKORGAN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PERCUSSIVE_ORGAN				= $12
SIDSETPROGRAM13:
    DEC A
    JR NZ, SIDSETPROGRAM14
    CALL SIDROCKORGAN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ROCK_ORGAN					= $13
SIDSETPROGRAM14:
    DEC A
    JR NZ, SIDSETPROGRAM15
    CALL SIDROCKORGAN
    JP SIDSETPROGRAMNN   
; IMF_INSTRUMENT_CHURCH_ORGAN					= $14
SIDSETPROGRAM15:
    DEC A
    JR NZ, SIDSETPROGRAM16
    CALL SIDROCKORGAN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_REED_ORGAN					= $15
SIDSETPROGRAM16:
    DEC A
    JR NZ, SIDSETPROGRAM17
    CALL SIDROCKORGAN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ACCORDION					= $16
SIDSETPROGRAM17:
    DEC A
    JR NZ, SIDSETPROGRAM18
    CALL SIDACCORDION
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_HARMONICA					= $17
SIDSETPROGRAM18:
    DEC A
    JR NZ, SIDSETPROGRAM19
    CALL SIDROCKORGAN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TANGO_ACCORDION				= $18
SIDSETPROGRAM19:
    DEC A
    JR NZ, SIDSETPROGRAM1A
    CALL SIDGUITAR
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ACOUSTIC_GUITAR_NYLON			= $19
SIDSETPROGRAM1A:
    DEC A
    JR NZ, SIDSETPROGRAM1B
    CALL SIDGUITAR
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ACOUSTIC_GUITAR_STEEL			= $1A
SIDSETPROGRAM1B:
    DEC A
    JR NZ, SIDSETPROGRAM1C
    CALL SIDGUITAR
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ELECTRIC_GUITAR_JAZZ			= $1B
SIDSETPROGRAM1C:
    DEC A
    JR NZ, SIDSETPROGRAM1D
    CALL SIDGUITAR
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ELECTRIC_GUITAR_CLEAN			= $1C
SIDSETPROGRAM1D:
    DEC A
    JR NZ, SIDSETPROGRAM1E
    CALL SIDGUITARMUTED
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ELECTRIC_GUITAR_MUTED			= $1D
SIDSETPROGRAM1E:
    DEC A
    JR NZ, SIDSETPROGRAM1F
    CALL SIDGUITAR
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_OVERDRIVEN_GUITAR			= $1E
SIDSETPROGRAM1F:
    DEC A
    JR NZ, SIDSETPROGRAM20
    CALL SIDGUITAR
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_DISTORTION_GUITAR			= $1F
SIDSETPROGRAM20:
    DEC A
    JR NZ, SIDSETPROGRAM21
    CALL SIDGUITAR
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_GUITAR_HARMONICS				= $20
SIDSETPROGRAM21:
    DEC A
    JR NZ, SIDSETPROGRAM22
    CALL SIDBASS
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ACOUSTIC_BASS				= $21
SIDSETPROGRAM22:
    DEC A
    JR NZ, SIDSETPROGRAM23
    CALL SIDBASS
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ELECTRIC_BASS_FINGER			= $22
SIDSETPROGRAM23:
    DEC A
    JR NZ, SIDSETPROGRAM24
    CALL SIDBASS
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ELECTRIC_BASS_PICK			= $23
SIDSETPROGRAM24:
    DEC A
    JR NZ, SIDSETPROGRAM25
    CALL SIDBASS
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FRETLESS_BASS				= $24
SIDSETPROGRAM25:
    DEC A
    JR NZ, SIDSETPROGRAM26
    CALL SIDBASS
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SLAP_BASS_1					= $25
SIDSETPROGRAM26:
    DEC A
    JR NZ, SIDSETPROGRAM27
    CALL SIDBASS
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SLAP_BASS_2					= $26
SIDSETPROGRAM27:
    DEC A
    JR NZ, SIDSETPROGRAM28
    CALL SIDBASS
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SYNTH_BASS_1					= $27
SIDSETPROGRAM28:
    DEC A
    JR NZ, SIDSETPROGRAM29
    CALL SIDBASS
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SYNTH_BASS_2					= $28
SIDSETPROGRAM29:
    DEC A
    JR NZ, SIDSETPROGRAM2A
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_VIOLIN						= $29
SIDSETPROGRAM2A:
    DEC A
    JR NZ, SIDSETPROGRAM2B
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_VIOLA						= $2A
SIDSETPROGRAM2B:
    DEC A
    JR NZ, SIDSETPROGRAM2C
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_CELLO						= $2B
SIDSETPROGRAM2C:
    DEC A
    JR NZ, SIDSETPROGRAM2D
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_CONTRABASS					= $2C
SIDSETPROGRAM2D:
    DEC A
    JR NZ, SIDSETPROGRAM2E
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TREMOLO_STRINGS				= $2D
SIDSETPROGRAM2E:
    DEC A
    JR NZ, SIDSETPROGRAM2F
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PIZZICATO_STRINGS			= $2E
SIDSETPROGRAM2F:
    DEC A
    JR NZ, SIDSETPROGRAM30
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ORCHESTRAL_HARP				= $2F
SIDSETPROGRAM30:
    DEC A
    JR NZ, SIDSETPROGRAM31
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TIMPANI						= $30
SIDSETPROGRAM31:
    DEC A
    JR NZ, SIDSETPROGRAM32
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_STRING_ENSEMBLE_1			= $31
SIDSETPROGRAM32:
    DEC A
    JR NZ, SIDSETPROGRAM33
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_STRING_ENSEMBLE_2			= $32
SIDSETPROGRAM33:
    DEC A
    JR NZ, SIDSETPROGRAM34
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SYNTHSTRINGS_1				= $33
SIDSETPROGRAM34:
    DEC A
    JR NZ, SIDSETPROGRAM35
    CALL SIDVIOLIN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SYNTHSTRINGS_2				= $34
SIDSETPROGRAM35:
    DEC A
    JR NZ, SIDSETPROGRAM36
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_CHOIR_AAHS					= $35
SIDSETPROGRAM36:
    DEC A
    JR NZ, SIDSETPROGRAM37
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_VOICE_OOHS					= $36
SIDSETPROGRAM37:
    DEC A
    JR NZ, SIDSETPROGRAM38
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SYNTH_VOICE					= $37
SIDSETPROGRAM38:
    DEC A
    JR NZ, SIDSETPROGRAM39
    CALL SIDROCKORGAN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ORCHESTRA_HIT				= $38
SIDSETPROGRAM39:
    DEC A
    JR NZ, SIDSETPROGRAM3A
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TRUMPET						= $39
SIDSETPROGRAM3A:
    DEC A
    JR NZ, SIDSETPROGRAM3B
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TROMBONE						= $3A
SIDSETPROGRAM3B:
    DEC A
    JR NZ, SIDSETPROGRAM3C
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TUBA							= $3B
SIDSETPROGRAM3C:
    DEC A
    JR NZ, SIDSETPROGRAM3D
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_MUTED_TRUMPET				= $3C
SIDSETPROGRAM3D:
    DEC A
    JR NZ, SIDSETPROGRAM3E
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FRENCH_HORN					= $3D
SIDSETPROGRAM3E:
    DEC A
    JR NZ, SIDSETPROGRAM3F
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_BRASS_SECTION				= $3E
SIDSETPROGRAM3F:
    DEC A
    JR NZ, SIDSETPROGRAM40
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SYNTHBRASS_1					= $3F
SIDSETPROGRAM40:
    DEC A
    JR NZ, SIDSETPROGRAM41
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SYNTHBRASS_2					= $40
SIDSETPROGRAM41:
    DEC A
    JR NZ, SIDSETPROGRAM42
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SOPRANO_SAX					= $41
SIDSETPROGRAM42:
    DEC A
    JR NZ, SIDSETPROGRAM43
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ALTO_SAX						= $42
SIDSETPROGRAM43:
    DEC A
    JR NZ, SIDSETPROGRAM44
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TENOR_SAX					= $43
SIDSETPROGRAM44:
    DEC A
    JR NZ, SIDSETPROGRAM45
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_BARITONE_SAX					= $44
SIDSETPROGRAM45:
    DEC A
    JR NZ, SIDSETPROGRAM46
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_OBOE							= $45
SIDSETPROGRAM46:
    DEC A
    JR NZ, SIDSETPROGRAM47
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_ENGLISH_HORN					= $46
SIDSETPROGRAM47:
    DEC A
    JR NZ, SIDSETPROGRAM48
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_BASSOON						= $47
SIDSETPROGRAM48:
    DEC A
    JR NZ, SIDSETPROGRAM49
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_CLARINET						= $48
SIDSETPROGRAM49:
    DEC A
    JR NZ, SIDSETPROGRAM4A
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PICCOLO						= $49
SIDSETPROGRAM4A:
    DEC A
    JR NZ, SIDSETPROGRAM4B
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FLUTE						= $4A
SIDSETPROGRAM4B:
    DEC A
    JR NZ, SIDSETPROGRAM4C
    CALL SIDFLUTE
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_RECORDER						= $4B
SIDSETPROGRAM4C:
    DEC A
    JR NZ, SIDSETPROGRAM4D
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PAN_FLUTE					= $4C
SIDSETPROGRAM4D:
    DEC A
    JR NZ, SIDSETPROGRAM4E
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_BLOWN_BOTTLE					= $4D
SIDSETPROGRAM4E:
    DEC A
    JR NZ, SIDSETPROGRAM4F
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SHAKUHACHI					= $4E
SIDSETPROGRAM4F:
    DEC A
    JR NZ, SIDSETPROGRAM50
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_WHISTLE						= $4F
SIDSETPROGRAM50:
    DEC A
    JR NZ, SIDSETPROGRAM51
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_OCARINA						= $50
SIDSETPROGRAM51:
    DEC A
    JR NZ, SIDSETPROGRAM52
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_LEAD_1_SQUARE				= $51
SIDSETPROGRAM52:
    DEC A
    JR NZ, SIDSETPROGRAM53
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_LEAD_2_SAWTOOTH				= $52
SIDSETPROGRAM53:
    DEC A
    JR NZ, SIDSETPROGRAM54
    CALL SIDCALLIOPE
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_LEAD_3_CALLIOPE				= $53
SIDSETPROGRAM54:
    DEC A
    JR NZ, SIDSETPROGRAM55
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_LEAD_4_CHIFF					= $54
SIDSETPROGRAM55:
    DEC A
    JR NZ, SIDSETPROGRAM56
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_LEAD_5_CHARANG				= $55
SIDSETPROGRAM56:
    DEC A
    JR NZ, SIDSETPROGRAM57
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_LEAD_6_VOICE					= $56
SIDSETPROGRAM57:
    DEC A
    JR NZ, SIDSETPROGRAM58
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_LEAD_7_FIFTHS				= $57
SIDSETPROGRAM58:
    DEC A
    JR NZ, SIDSETPROGRAM59
    CALL SIDGUITAR
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_LEAD_8_BASS_LEAD				= $58
SIDSETPROGRAM59:
    DEC A
    JR NZ, SIDSETPROGRAM5A
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PAD_1_NEW_AGE				= $59
SIDSETPROGRAM5A:
    DEC A
    JR NZ, SIDSETPROGRAM5B
    CALL SIDTRUMPET
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PAD_2_WARM					= $5A
SIDSETPROGRAM5B:
    DEC A
    JR NZ, SIDSETPROGRAM5C
    CALL SIDROCKORGAN
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PAD_3_POLYSYNTH				= $5B
SIDSETPROGRAM5C:
    DEC A
    JR NZ, SIDSETPROGRAM5D
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PAD_4_CHOIR					= $5C
SIDSETPROGRAM5D:
    DEC A
    JR NZ, SIDSETPROGRAM5E
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PAD_5_BOWED					= $5D
SIDSETPROGRAM5E:
    DEC A
    JR NZ, SIDSETPROGRAM5F
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PAD_6_METALLIC				= $5E
SIDSETPROGRAM5F:
    DEC A
    JR NZ, SIDSETPROGRAM60
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PAD_7_HALO					= $5F
SIDSETPROGRAM60:
    DEC A
    JR NZ, SIDSETPROGRAM61
    CALL SIDPIANO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_PAD_8_SWEEP					= $60
SIDSETPROGRAM61:
    DEC A
    JR NZ, SIDSETPROGRAM62
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FX_1_RAIN					= $61
SIDSETPROGRAM62:
    DEC A
    JR NZ, SIDSETPROGRAM63
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FX_2_SOUNDTRACK				= $62
SIDSETPROGRAM63:
    DEC A
    JR NZ, SIDSETPROGRAM64
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FX_3_CRYSTAL					= $63
SIDSETPROGRAM64:
    DEC A
    JR NZ, SIDSETPROGRAM65
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FX_4_ATMOSPHERE				= $64
SIDSETPROGRAM65:
    DEC A
    JR NZ, SIDSETPROGRAM66
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FX_5_BRIGHTNESS				= $65
SIDSETPROGRAM66:
    DEC A
    JR NZ, SIDSETPROGRAM67
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FX_6_GOBLINS					= $66
SIDSETPROGRAM67:
    DEC A
    JR NZ, SIDSETPROGRAM68
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FX_7_ECHOES					= $67
SIDSETPROGRAM68:
    DEC A
    JR NZ, SIDSETPROGRAM69
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FX_8_SCI_FI					= $68
SIDSETPROGRAM69:
    DEC A
    JR NZ, SIDSETPROGRAM6A
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SITAR						= $69
SIDSETPROGRAM6A:
    DEC A
    JR NZ, SIDSETPROGRAM6B
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_BANJO						= $6A
SIDSETPROGRAM6B:
    DEC A
    JR NZ, SIDSETPROGRAM6C
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SHAMISEN						= $6B
SIDSETPROGRAM6C:
    DEC A
    JR NZ, SIDSETPROGRAM6D
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_KOTO							= $6C
SIDSETPROGRAM6D:
    DEC A
    JR NZ, SIDSETPROGRAM6E
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_KALIMBA						= $6D
SIDSETPROGRAM6E:
    DEC A
    JR NZ, SIDSETPROGRAM6F
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_BAG_PIPE						= $6E
SIDSETPROGRAM6F:
    DEC A
    JR NZ, SIDSETPROGRAM70
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_FIDDLE						= $6F
SIDSETPROGRAM70:
    DEC A
    JR NZ, SIDSETPROGRAM71
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SHANAI						= $70
SIDSETPROGRAM71:
    DEC A
    JR NZ, SIDSETPROGRAM72
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TINKLE_BELL					= $71
SIDSETPROGRAM72:
    DEC A
    JR NZ, SIDSETPROGRAM73
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_AGOGO						= $72
SIDSETPROGRAM73:
    DEC A
    JR NZ, SIDSETPROGRAM74
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_STEEL_DRUMS					= $73
SIDSETPROGRAM74:
    DEC A
    JR NZ, SIDSETPROGRAM75
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_WOODBLOCK					= $74
SIDSETPROGRAM75:
    DEC A
    JR NZ, SIDSETPROGRAM76
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TAIKO_DRUM					= $75
SIDSETPROGRAM76:
    DEC A
    JR NZ, SIDSETPROGRAM77
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_MELODIC_TOM					= $76
SIDSETPROGRAM77:
    DEC A
    JR NZ, SIDSETPROGRAM78
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SYNTH_DRUM					= $77
SIDSETPROGRAM78:
    DEC A
    JR NZ, SIDSETPROGRAM79
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_REVERSE_CYMBAL				= $78
SIDSETPROGRAM79:
    DEC A
    JR NZ, SIDSETPROGRAM7A
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_GUITAR_FRET_NOISE			= $79
SIDSETPROGRAM7A:
    DEC A
    JR NZ, SIDSETPROGRAM7B
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_BREATH_NOISE					= $7A
SIDSETPROGRAM7B:
    DEC A
    JR NZ, SIDSETPROGRAM7C
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_SEASHORE						= $7B
SIDSETPROGRAM7C:
    DEC A
    JR NZ, SIDSETPROGRAM7D
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_BIRD_TWEET					= $7C
SIDSETPROGRAM7D:
    DEC A
    JR NZ, SIDSETPROGRAM7E
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_TELEPHONE_RING				= $7D
SIDSETPROGRAM7E:
    DEC A
    JR NZ, SIDSETPROGRAM7F
    CALL SIDBANJO
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_HELICOPTER					= $7E
SIDSETPROGRAM7F:
    DEC A
    JR NZ, SIDSETPROGRAM80
    CALL SIDTIMPANI
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_APPLAUSE						= $7F
SIDSETPROGRAM80:
    DEC A
    JR NZ, SIDSETPROGRAM81
    CALL SIDGUNSHOT
    JP SIDSETPROGRAMNN
; IMF_INSTRUMENT_GUNSHOT						= $80
SIDSETPROGRAM81:
SIDSETPROGRAMNN:
    RET

SIDMUSICLOOP: DEFB $0
SIDMUSICREADY: DEFB $0
SIDMUSICPAUSE: DEFB $0
SIDBLOCKS: DEFW $0
SIDLASTBLOCK: DEFB $0

SIDBLOCKS_BACKUP: DEFW $0
SIDLASTBLOCK_BACKUP: DEFB $0
SIDTMPPTR_BACKUP: DEFW $0

SIDTMPPTR = $05 ; $06
SIDTMPOFS = $07
SIDTMPLEN = $08
SIDJIFFIES = $09 ; $0A

MUSICPLAYERRESET:
    LD A, $0
    LD (SIDJIFFIES), A
    LD (SIDTMPOFS), A
    LD A, $1
    LD (SIDMUSICREADY), A
    LD A, SIDTMPPTR_BACKUP
    LD (SIDTMPPTR), A
    LD A, SIDTMPPTR_BACKUP+1
    LD (SIDTMPPTR+1), A
    LD A, SIDLASTBLOCK_BACKUP
    LD (SIDLASTBLOCK), A
    LD A, SIDBLOCKS_BACKUP
    LD (SIDBLOCKS), A
    CP 0
    JR Z, MUSICPLAYERRESET3
    LD A, $FF
    JP MUSICPLAYERRESET2
MUSICPLAYERRESET3:
    LD A, SIDLASTBLOCK_BACKUP
MUSICPLAYERRESET2:
    LD (SIDTMPLEN), A
    RET

; This is the entry point for music play routine
; using the interrupt. 
MUSICPLAYER:
    PUSH AF
    LD A, (SIDMUSICREADY)
    CP 0
    JR Z, MUSICPLAYERQ2
    LD A, (SIDMUSICPAUSE)
    JR NZ, MUSICPLAYERQ2
    LD A, C
    PUSH AF
    LD A, B
    PUSH AF
    CALL MUSICPLAYERR
    POP AF
    LD B, A
    POP AF
    LD C, A
MUSICPLAYERQ2:
    POP AF
    RET

MUSICPLAYERR:

; This is the entry point to wait until the waiting jiffies
; are exausted.
MUSICPLAYERL1:
    LD A, (SIDJIFFIES)
    CP 0
    JR Z, MUSICPLAYERL1B
    DEC A
    LD (SIDJIFFIES), A
    RET

; This is the entry point to read the next instruction.
MUSICPLAYERL1B:
    ; Read the next byte.
    CALL MUSICREADNEXTBYTE

    ; Is the file NOT finished?
    LD A, C
    CP 0
    JR NZ, MUSICPLAYERL1X

    ; Is a LOOP requested?
    LD A, (SIDMUSICLOOP)
    CP 0
    JR Z, MUSICPLAYERL1BDONE

    CALL MUSICPLAYERRESET
    RET

MUSICPLAYERL1BDONE:
    ; Let's stop the play!
    LD A, $0
    LD (SIDMUSICREADY), A
    LD (SIDTMPPTR), A
    LD (SIDTMPPTR+1), A
    LD (SIDJIFFIES), A
    RET

; This is the entry point to decode the instruction
; (contained into the A register).
MUSICPLAYERL1X:
    SLA A
    JR C, MUSICPLAYERL1X0
    JP MUSICWAIT
MUSICPLAYERL1X0:
    SLA A
    JR C, MUSICPLAYERL1X0A
    JP MUSICSETPROGRAM
MUSICPLAYERL1X0A:
    SLA A
    JR C, MUSICPLAYERL1X1
    JP MUSICNOTEON
MUSICPLAYERL1X1:
    SLA A
    JR C, MUSICPLAYERL1X2
    JP MUSICNOTEOFF
MUSICPLAYERL1X2:
    RET

MUSICWAIT:
    SRL A
    LD (SIDJIFFIES), A
    RET

MUSICSETPROGRAM:
    SRL A
    SRL A
    LD (MUSICTMP), A
    CALL MUSICREADNEXTBYTE
    PUSH AF
    LD A, (MUSICTMP)
    LD C, A
    POP AF
    CALL SIDSETPROGRAM
    JP MUSICPLAYERL1B

MUSICNOTEOFF:
    SRL A
    SRL A
    SRL A
    SRL A
    CALL SIDSTOP
    JP MUSICPLAYERL1B

MUSICNOTEON:
    SRL A
    SRL A
    SRL A
    PUSH AF
    CALL MUSICREADNEXTBYTE
    SLA A
    LD HL, (SIDTMPPTR2)
    LD E, A
    LD D, 0
    ADD HL, DE
    LD A, (HL)
    LD C, A
    INC HL
    LD A, (HL)
    LD B, A
    POP AF
    PUSH AF
    CALL SIDPROGFREQ
    POP AF
    PUSH AF
    CALL MUSICREADNEXTBYTE
    POP AF
    JP MUSICPLAYERL1B

; This routine has been added in order to read the
; next byte in a "blocked" byte stream.
MUSICREADNEXTBYTE:
    ; Let's check if we arrived at the end of the block.
    ; In that case, we must "load" the next block (or end
    ; the reading).
    LD B, (SIDTMPOFS)
    CPY SIDTMPLEN
    JR Z, MUSICREADNEXTBYTELE

MUSICREADNEXTBYTE2:
    LD C, $ff
    LD HL, (SIDTMPPTR) 
    LD A, B
    LD E, A
    LD D, 0
    ADD HL, DE
    LD A, (HL)
    INC B
    LD (SIDTMPOFS), B
    RET

; This is the entry point if a block (256 or less bytes)
; is finished, and we must move forward to the next block.
MUSICREADNEXTBYTELE:
    ; Is file finished?
    LD A, (SIDBLOCKS)
    CP 0
    JR Z, MUSICREADNEXTBYTEEND

    ; Increment the base address by 255
    LD A, (SIDTMPPTR+1)
    INC A
    LD (SIDTMPPTR+1), A
    LD A, (SIDTMPPTR)
    DEC A
    LD (SIDTMPPTR), A

    ; Decrement the number of remaining blocks
    LD A, (SIDBLOCKS)
    DEC A
    LD (SIDBLOCKS), A

    ; If remaining blocks are 0, the last block
    ; length is different from 256 bytes.

    LD A, (SIDBLOCKS)
    JR Z, MUSICPLAYERLE2

    ; Remaining block is 256 bytes lenght.
    LD B, $ff
    LD (SIDTMPLEN), B

    ; Put the index to 0
    LD B, $0
    LD (SIDTMPOFS), B

    JP MUSICREADNEXTBYTE2

    ; Remaining block is <256 bytes lenght.
MUSICPLAYERLE2:
    LD B, (SIDLASTBLOCK)
    LD (SIDTMPLEN), B

    ; Put the index to 0
    LD B, $0
    LD (SIDTMPOFS), B

    JP MUSICREADNEXTBYTE2

MUSICREADNEXTBYTEEND:
    LD C, $0
    RET
